# Generated by Django 5.2.8 on 2025-11-25 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الزبون')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='اسم الزبون')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='اسم الزبون')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الشركة')),
                ('company_name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة')),
                ('company_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة')),
                ('tax_number', models.CharField(blank=True, help_text='اختياري: رقم ضريبة القيمة المضافة أو الرقم الضريبي إن وجد.', max_length=50, verbose_name='الرقم الضريبي / ضريبة القيمة المضافة')),
                ('country', models.CharField(blank=True, help_text='اسم الدولة (يمكن ترجمته).', max_length=255, verbose_name='الدولة')),
                ('country_ar', models.CharField(blank=True, help_text='اسم الدولة (يمكن ترجمته).', max_length=255, null=True, verbose_name='الدولة')),
                ('country_en', models.CharField(blank=True, help_text='اسم الدولة (يمكن ترجمته).', max_length=255, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, help_text='اسم المحافظة (يمكن ترجمته).', max_length=255, verbose_name='المحافظة')),
                ('governorate_ar', models.CharField(blank=True, help_text='اسم المحافظة (يمكن ترجمته).', max_length=255, null=True, verbose_name='المحافظة')),
                ('governorate_en', models.CharField(blank=True, help_text='اسم المحافظة (يمكن ترجمته).', max_length=255, null=True, verbose_name='المحافظة')),
                ('wilaya', models.CharField(blank=True, help_text='اسم الولاية (يمكن ترجمته).', max_length=255, verbose_name='الولاية')),
                ('wilaya_ar', models.CharField(blank=True, help_text='اسم الولاية (يمكن ترجمته).', max_length=255, null=True, verbose_name='الولاية')),
                ('wilaya_en', models.CharField(blank=True, help_text='اسم الولاية (يمكن ترجمته).', max_length=255, null=True, verbose_name='الولاية')),
                ('village', models.CharField(blank=True, help_text='اسم القرية أو الحي (يمكن ترجمته).', max_length=255, verbose_name='القرية / الحي')),
                ('village_ar', models.CharField(blank=True, help_text='اسم القرية أو الحي (يمكن ترجمته).', max_length=255, null=True, verbose_name='القرية / الحي')),
                ('village_en', models.CharField(blank=True, help_text='اسم القرية أو الحي (يمكن ترجمته).', max_length=255, null=True, verbose_name='القرية / الحي')),
                ('postal_code', models.CharField(blank=True, help_text='الرمز البريدي (يمكن ترجمته عند الحاجة).', max_length=20, verbose_name='الرمز البريدي')),
                ('postal_code_ar', models.CharField(blank=True, help_text='الرمز البريدي (يمكن ترجمته عند الحاجة).', max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('postal_code_en', models.CharField(blank=True, help_text='الرمز البريدي (يمكن ترجمته عند الحاجة).', max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('po_box', models.CharField(blank=True, help_text='رقم صندوق البريد (يمكن ترجمته عند الحاجة).', max_length=20, verbose_name='صندوق البريد')),
                ('po_box_ar', models.CharField(blank=True, help_text='رقم صندوق البريد (يمكن ترجمته عند الحاجة).', max_length=20, null=True, verbose_name='صندوق البريد')),
                ('po_box_en', models.CharField(blank=True, help_text='رقم صندوق البريد (يمكن ترجمته عند الحاجة).', max_length=20, null=True, verbose_name='صندوق البريد')),
                ('address', models.TextField(blank=True, verbose_name='العنوان الكامل (نصي)')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان الكامل (نصي)')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='العنوان الكامل (نصي)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(blank=True, help_text='اختياري: ربط الزبون بحساب مستخدم للدخول إلى البوابة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'الزبون',
                'verbose_name_plural': 'الزبائن',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='اسم قصير للتمييز بين العناوين: المكتب الرئيسي، المخزن، الموقع 1...', max_length=100, verbose_name='وصف العنوان')),
                ('type', models.CharField(choices=[('billing', 'عنوان الفوترة'), ('shipping', 'عنوان الشحن'), ('other', 'عنوان آخر')], default='billing', max_length=20, verbose_name='نوع العنوان')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='الدولة')),
                ('country_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('country_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, max_length=255, verbose_name='المحافظة')),
                ('governorate_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('governorate_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('wilaya', models.CharField(blank=True, max_length=255, verbose_name='الولاية')),
                ('wilaya_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('wilaya_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('village', models.CharField(blank=True, max_length=255, verbose_name='القرية / الحي')),
                ('village_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / الحي')),
                ('village_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / الحي')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('postal_code_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('postal_code_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('po_box', models.CharField(blank=True, max_length=20, verbose_name='صندوق البريد')),
                ('po_box_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد')),
                ('po_box_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد')),
                ('is_primary', models.BooleanField(default=False, help_text='إذا كان مفعّلًا، يُعتبر العنوان الأساسي لهذا النوع (فوترة / شحن).', verbose_name='عنوان أساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.customer', verbose_name='الزبون')),
            ],
            options={
                'verbose_name': 'عنوان زبون',
                'verbose_name_plural': 'عناوين الزبائن',
                'ordering': ('customer', 'type', '-is_primary', 'id'),
            },
        ),
    ]
