# Generated by Django 5.2.8 on 2025-12-09 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'فرد'), ('company', 'شركة')], default='person', max_length=20, verbose_name='نوع جهة الاتصال')),
                ('name', models.CharField(help_text='اسم الشخص أو اسم الشركة.', max_length=255, verbose_name='الاسم')),
                ('name_ar', models.CharField(help_text='اسم الشخص أو اسم الشركة.', max_length=255, null=True, verbose_name='الاسم')),
                ('name_en', models.CharField(help_text='اسم الشخص أو اسم الشركة.', max_length=255, null=True, verbose_name='الاسم')),
                ('company_name', models.CharField(blank=True, help_text='يُستخدم للعرض حتى لو لم تربطه بسجل شركة في جهات الاتصال.', max_length=255, verbose_name='اسم الشركة (نص حر)')),
                ('company_name_ar', models.CharField(blank=True, help_text='يُستخدم للعرض حتى لو لم تربطه بسجل شركة في جهات الاتصال.', max_length=255, null=True, verbose_name='اسم الشركة (نص حر)')),
                ('company_name_en', models.CharField(blank=True, help_text='يُستخدم للعرض حتى لو لم تربطه بسجل شركة في جهات الاتصال.', max_length=255, null=True, verbose_name='اسم الشركة (نص حر)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي / VAT')),
                ('is_customer', models.BooleanField(default=False, verbose_name='زبون')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='مورد / شريك')),
                ('is_owner', models.BooleanField(default=False, verbose_name='مالك')),
                ('is_employee', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(blank=True, help_text='اربط هذا الشخص بسجل شركة في جهات الاتصال.', limit_choices_to={'kind': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='contacts.contact', verbose_name='الشركة (جهة اتصال)')),
                ('user', models.OneToOneField(blank=True, help_text='ربط جهة الاتصال بحساب مستخدم (بوابة العملاء/الموظفين).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (اختياري)')),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'عنوان فوترة'), ('shipping', 'عنوان شحن'), ('office', 'مكتب / مقر'), ('other', 'عنوان آخر')], default='other', max_length=20, verbose_name='نوع العنوان')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='الدولة')),
                ('country_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('country_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, max_length=255, verbose_name='المحافظة')),
                ('governorate_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('governorate_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('wilaya', models.CharField(blank=True, max_length=255, verbose_name='الولاية')),
                ('wilaya_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('wilaya_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('village', models.CharField(blank=True, max_length=255, verbose_name='القرية / المنطقة')),
                ('village_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة')),
                ('village_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('po_box', models.CharField(blank=True, max_length=20, verbose_name='صندوق البريد')),
                ('is_primary', models.BooleanField(default=False, verbose_name='العنوان الرئيسي لهذا النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.contact', verbose_name='جهة الاتصال')),
            ],
            options={
                'verbose_name': 'عنوان جهة اتصال',
                'verbose_name_plural': 'عناوين جهات الاتصال',
                'ordering': ('contact', 'address_type', '-is_primary', 'id'),
            },
        ),
    ]
