# Generated by Django 5.2.8 on 2025-11-25 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name', 'id'), 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ('customer', 'type', '-is_primary', 'id'), 'verbose_name': 'عنوان عميل', 'verbose_name_plural': 'عناوين العملاء'},
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='label_ar',
            field=models.CharField(help_text='مثال: المكتب الرئيسي، المخزن، الموقع 1...', max_length=100, null=True, verbose_name='وصف العنوان'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='label_en',
            field=models.CharField(help_text='مثال: المكتب الرئيسي، المخزن، الموقع 1...', max_length=100, null=True, verbose_name='وصف العنوان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='عنوان تفصيلي (حر)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_ar',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان تفصيلي (حر)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان تفصيلي (حر)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, help_text='اسم الدولة (سيتم تعريبه بالـ modeltranslation).', max_length=255, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_ar',
            field=models.CharField(blank=True, help_text='اسم الدولة (سيتم تعريبه بالـ modeltranslation).', max_length=255, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_en',
            field=models.CharField(blank=True, help_text='اسم الدولة (سيتم تعريبه بالـ modeltranslation).', max_length=255, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='governorate',
            field=models.CharField(blank=True, max_length=255, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='governorate_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='governorate_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='po_box',
            field=models.CharField(blank=True, max_length=20, verbose_name='صندوق البريد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='po_box_ar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='po_box_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code_ar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, help_text='اختياري: الرقم الضريبي إذا وُجد.', max_length=50, verbose_name='الرقم الضريبي / VAT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='ربط العميل بحساب مستخدم للدخول إلى البوابة (إن وجد).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (اختياري)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='village',
            field=models.CharField(blank=True, max_length=255, verbose_name='القرية / المنطقة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='village_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='village_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wilaya',
            field=models.CharField(blank=True, max_length=255, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wilaya_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wilaya_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='إذا مفعّل، يُعتبر العنوان الرئيسي لنوعه (فوترة/شحن).', verbose_name='العنوان الرئيسي لهذا النوع'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(help_text='مثال: المكتب الرئيسي، المخزن، الموقع 1...', max_length=100, verbose_name='وصف العنوان'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='type',
            field=models.CharField(choices=[('billing', 'عنوان فوترة'), ('shipping', 'عنوان شحن'), ('other', 'عنوان آخر')], default='billing', max_length=20, verbose_name='نوع العنوان'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='village',
            field=models.CharField(blank=True, max_length=255, verbose_name='القرية / المنطقة'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='village_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='village_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة'),
        ),
    ]
