# Generated by Django 5.2.8 on 2025-11-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_customer_options_alter_customeraddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='customer',
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'فرد'), ('company', 'شركة')], default='person', max_length=20, verbose_name='نوع الكونتاكت')),
                ('name', models.CharField(help_text='اسم الشخص أو اسم الشركة.', max_length=255, verbose_name='الاسم')),
                ('name_ar', models.CharField(help_text='اسم الشخص أو اسم الشركة.', max_length=255, null=True, verbose_name='الاسم')),
                ('name_en', models.CharField(help_text='اسم الشخص أو اسم الشركة.', max_length=255, null=True, verbose_name='الاسم')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='اسم الشركة (إن وجد)')),
                ('company_name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة (إن وجد)')),
                ('company_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة (إن وجد)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي / VAT')),
                ('is_customer', models.BooleanField(default=False, verbose_name='زبون')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='مورد / شريك')),
                ('is_owner', models.BooleanField(default=False, verbose_name='مالك')),
                ('is_employee', models.BooleanField(default=False, verbose_name='موظف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='الدولة')),
                ('country_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('country_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, max_length=255, verbose_name='المحافظة')),
                ('governorate_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('governorate_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('wilaya', models.CharField(blank=True, max_length=255, verbose_name='الولاية')),
                ('wilaya_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('wilaya_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('village', models.CharField(blank=True, max_length=255, verbose_name='القرية / المنطقة')),
                ('village_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة')),
                ('village_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('postal_code_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('postal_code_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('po_box', models.CharField(blank=True, max_length=20, verbose_name='صندوق البريد')),
                ('po_box_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد')),
                ('po_box_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد')),
                ('address', models.TextField(blank=True, verbose_name='عنوان تفصيلي (حر)')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='عنوان تفصيلي (حر)')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='عنوان تفصيلي (حر)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.OneToOneField(blank=True, help_text='ربط الكونتاكت بحساب مستخدم (بوابة العملاء/الموظفين).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (اختياري)')),
            ],
            options={
                'verbose_name': 'كونتاكت',
                'verbose_name_plural': 'الكونتاكتس',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثال: المكتب الرئيسي، المخزن، موقع المشروع 1...', max_length=100, verbose_name='وصف العنوان')),
                ('label_ar', models.CharField(help_text='مثال: المكتب الرئيسي، المخزن، موقع المشروع 1...', max_length=100, null=True, verbose_name='وصف العنوان')),
                ('label_en', models.CharField(help_text='مثال: المكتب الرئيسي، المخزن، موقع المشروع 1...', max_length=100, null=True, verbose_name='وصف العنوان')),
                ('address_type', models.CharField(choices=[('billing', 'عنوان فوترة'), ('shipping', 'عنوان شحن'), ('office', 'مكتب / مقر'), ('other', 'عنوان آخر')], default='other', max_length=20, verbose_name='نوع العنوان')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='الدولة')),
                ('country_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('country_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, max_length=255, verbose_name='المحافظة')),
                ('governorate_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('governorate_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='المحافظة')),
                ('wilaya', models.CharField(blank=True, max_length=255, verbose_name='الولاية')),
                ('wilaya_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('wilaya_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='الولاية')),
                ('village', models.CharField(blank=True, max_length=255, verbose_name='القرية / المنطقة')),
                ('village_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة')),
                ('village_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='القرية / المنطقة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('postal_code_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('postal_code_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('po_box', models.CharField(blank=True, max_length=20, verbose_name='صندوق البريد')),
                ('po_box_ar', models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد')),
                ('po_box_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='صندوق البريد')),
                ('is_primary', models.BooleanField(default=False, verbose_name='العنوان الرئيسي لهذا النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.contact', verbose_name='الكونتاكت')),
            ],
            options={
                'verbose_name': 'عنوان كونتاكت',
                'verbose_name_plural': 'عناوين الكونتاكت',
                'ordering': ('contact', 'address_type', '-is_primary', 'id'),
            },
        ),
    ]
