# Generated by Django 5.2.8 on 2025-11-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_invoice_customer_alter_order_customer_and_more'),
        ('contacts', '0003_remove_customer_user_remove_customeraddress_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
    ]
