# Generated by Django 5.2.8 on 2025-11-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_delete_customer_delete_customeraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('name', 'id'), 'verbose_name': 'جهة اتصال', 'verbose_name_plural': 'جهات الاتصال'},
        ),
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'ordering': ('contact', 'address_type', '-is_primary', 'id'), 'verbose_name': 'عنوان جهة اتصال', 'verbose_name_plural': 'عناوين جهات الاتصال'},
        ),
    ]
