# Generated by Django 5.2.8 on 2025-11-25 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_options_alter_contactaddress_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, help_text='اربط هذا الشخص بسجل شركة في جهات الاتصال.', limit_choices_to={'kind': 'company'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='contacts.contact', verbose_name='الشركة (جهة اتصال)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, help_text='يُستخدم للعرض حتى لو لم تربطه بسجل شركة في جهات الاتصال.', max_length=255, verbose_name='اسم الشركة (نص حر)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name_ar',
            field=models.CharField(blank=True, help_text='يُستخدم للعرض حتى لو لم تربطه بسجل شركة في جهات الاتصال.', max_length=255, null=True, verbose_name='اسم الشركة (نص حر)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name_en',
            field=models.CharField(blank=True, help_text='يُستخدم للعرض حتى لو لم تربطه بسجل شركة في جهات الاتصال.', max_length=255, null=True, verbose_name='اسم الشركة (نص حر)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('person', 'فرد'), ('company', 'شركة')], default='person', max_length=20, verbose_name='نوع جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, help_text='ربط جهة الاتصال بحساب مستخدم (بوابة العملاء/الموظفين).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (اختياري)'),
        ),
        migrations.AlterField(
            model_name='contactaddress',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.contact', verbose_name='جهة الاتصال'),
        ),
    ]
