# Generated by Django 5.2.8 on 2025-11-24 15:01

import core.models.attachments
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('status_change', 'تغيير حالة'), ('notification', 'إشعار'), ('other', 'أخرى')], max_length=32, verbose_name='العملية')),
                ('target_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField(blank=True, verbose_name='الوصف')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('verb', models.CharField(help_text="Short description of the event, e.g. 'New order created'.", max_length=255, verbose_name='Verb')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('url', models.CharField(blank=True, help_text='Resolved URL to redirect when the notification is clicked.', max_length=500)),
                ('target_object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_targets', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text='مثال: accounting.Invoice أو accounting.Order', max_length=100, verbose_name='اسم الموديل (label)')),
                ('field_name', models.CharField(default='number', help_text="عادة يكون 'number'.", max_length=50, verbose_name='اسم الحقل')),
                ('pattern', models.CharField(help_text='مثال: INV-{year}-{seq:04d} أو SO-{year}-{month:02d}-{seq:03d}', max_length=100, verbose_name='نمط الترقيم')),
                ('reset', models.CharField(choices=[('never', 'لا يتم إعادة الترقيم'), ('year', 'يُعاد سنوياً'), ('month', 'يُعاد شهرياً')], default='year', max_length=10, verbose_name='سياسة إعادة الترقيم')),
                ('start', models.PositiveIntegerField(default=1, verbose_name='قيمة البداية للتسلسل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعداد ترقيم',
                'verbose_name_plural': 'إعدادات الترقيم',
                'indexes': [models.Index(fields=['model_label'], name='core_number_model_l_7bd675_idx')],
                'unique_together': {('model_label', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('period', models.CharField(blank=True, max_length=16)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('key', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرّف الكيان')),
                ('file', models.FileField(upload_to=core.models.attachments.attachment_upload_to, verbose_name='الملف')),
                ('title', models.CharField(blank=True, help_text='اسم داخلي يساعدك على تمييز المرفق.', max_length=255, verbose_name='عنوان المرفق')),
                ('description', models.TextField(blank=True, help_text='ملاحظات إضافية حول المرفق (اختياري).', verbose_name='وصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_public', models.BooleanField(default=True, help_text='يمكن استخدامه لاحقًا لفلترة المرفقات في البورتال/الويب.', verbose_name='مرئي للواجهة؟')),
                ('is_active', models.BooleanField(default=True, help_text='بدلاً من الحذف النهائي، يمكنك إلغاء التفعيل لإخفاء المرفق.', verbose_name='مفعّل')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contenttypes.contenttype', verbose_name='نوع الكيان')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx'), models.Index(fields=['uploaded_at'], name='core_attach_uploade_e6a864_idx'), models.Index(fields=['is_active'], name='core_attach_is_acti_797545_idx')],
            },
        ),
    ]
