# Generated by Django 5.2.8 on 2025-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberingscheme',
            name='model_label',
            field=models.CharField(help_text='مثال: accounting.Invoice أو accounting.Order', max_length=100, verbose_name='اسم الموديل (label)'),
        ),
        migrations.AlterUniqueTogether(
            name='numberingscheme',
            unique_together={('model_label', 'field_name')},
        ),
    ]
