# Generated by Django 5.2.8 on 2025-12-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('status_change', 'تغيير حالة'), ('notification', 'إشعار'), ('other', 'أخرى')], db_index=True, max_length=32, verbose_name='العملية'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='المستخدم الذي قام بهذه العملية إن وُجد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contenttypes.contenttype', verbose_name='نوع الكائن'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='معرّف الكائن'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='core_auditl_actor_i_41600a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_content_type', 'target_object_id', 'created_at'], name='core_auditl_target__5bd7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'),
        ),
    ]
