# Generated by Django 5.2.8 on 2025-11-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.CharField(blank=True, help_text="Logical context for this notification, e.g. 'staff', 'customer'.", max_length=50),
        ),
    ]
