# Generated by Django 5.2.8 on 2025-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(help_text='مثال: accounting.Invoice أو accounting.Order', max_length=100, unique=True, verbose_name='اسم الموديل (label)')),
                ('field_name', models.CharField(default='number', help_text="عادة يكون 'number'.", max_length=50, verbose_name='اسم الحقل')),
                ('pattern', models.CharField(help_text='مثال: INV-{year}-{seq:04d} أو SO-{year}-{month:02d}-{seq:03d}', max_length=100, verbose_name='نمط الترقيم')),
                ('reset', models.CharField(choices=[('never', 'لا يتم إعادة الترقيم'), ('year', 'يُعاد سنوياً'), ('month', 'يُعاد شهرياً')], default='year', max_length=10, verbose_name='سياسة إعادة الترقيم')),
                ('start', models.PositiveIntegerField(default=1, verbose_name='قيمة البداية للتسلسل')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعداد ترقيم',
                'verbose_name_plural': 'إعدادات الترقيم',
            },
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('period', models.CharField(blank=True, max_length=16)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('key', 'period')},
            },
        ),
    ]
