# Generated by Django 5.2.8 on 2025-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='context',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='Resolved URL to redirect when the notification is clicked.', max_length=500),
        ),
    ]
