# Generated by Django 5.2.8 on 2025-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_numberingscheme_numbersequence'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='numberingscheme',
            index=models.Index(fields=['model_label'], name='core_number_model_l_7bd675_idx'),
        ),
    ]
