# Generated by Django 5.2.8 on 2025-11-19 16:57

import core.models.attachments
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_numberingscheme_core_number_model_l_7bd675_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='معرّف الكيان')),
                ('file', models.FileField(upload_to=core.models.attachments.attachment_upload_to, verbose_name='الملف')),
                ('title', models.CharField(blank=True, help_text='اسم داخلي يساعدك على تمييز المرفق.', max_length=255, verbose_name='عنوان المرفق')),
                ('description', models.TextField(blank=True, help_text='ملاحظات إضافية حول المرفق (اختياري).', verbose_name='وصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_public', models.BooleanField(default=True, help_text='إذا تم إيقافه يمكن استخدامه لاحقًا لفلترة المرفقات داخليًا.', verbose_name='مرئي للجميع؟')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contenttypes.contenttype', verbose_name='نوع الكيان')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx'), models.Index(fields=['uploaded_at'], name='core_attach_uploade_e6a864_idx')],
            },
        ),
    ]
