# Generated by Django 5.2.8 on 2025-11-19 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='بدلاً من الحذف النهائي، يمكنك إلغاء التفعيل لإخفاء المرفق.', verbose_name='مفعّل'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='is_public',
            field=models.BooleanField(default=True, help_text='يمكن استخدامه لاحقًا لفلترة المرفقات في البورتال/الويب.', verbose_name='مرئي للواجهة؟'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_active'], name='core_attach_is_acti_797545_idx'),
        ),
    ]
