# Generated by Django 5.2.8 on 2025-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_blogpost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
