# Generated by Django 5.2.8 on 2025-11-22 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الدفتر')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدفتر')),
                ('type', models.CharField(choices=[('general', 'دفتر عام'), ('cash', 'دفتر الكاش'), ('bank', 'دفتر البنك'), ('sales', 'دفتر المبيعات'), ('purchase', 'دفتر المشتريات')], default='general', max_length=20, verbose_name='نوع الدفتر')),
                ('is_default', models.BooleanField(default=False, verbose_name='دفتر افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دفتر اليومية',
                'verbose_name_plural': 'دفاتر اليومية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_settlement', models.BooleanField(default=True, help_text='Allow this account to be used in settlements.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مقفلة؟')),
                ('is_default', models.BooleanField(default=False, help_text='تُستخدم هذه السنة كافتراضي في التقارير عند عدم اختيار سنة أخرى.', verbose_name='سنة افتراضية للتقارير؟')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='fiscalyear_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='المرجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='رقم القيد')),
                ('posted', models.BooleanField(default=False, verbose_name='مرحّل')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.fiscalyear', verbose_name='السنة المالية')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.journal', verbose_name='دفتر اليومية')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='مُرحّل بواسطة')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('bank_journal', models.ForeignKey(blank=True, help_text='يستخدم لحركات حسابات البنك.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_bank_journal', to='ledger.journal', verbose_name='دفتر البنك')),
                ('cash_journal', models.ForeignKey(blank=True, help_text='يستخدم لحركات الصندوق النقدي.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_cash_journal', to='ledger.journal', verbose_name='دفتر الكاش')),
                ('closing_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود إقفال السنة المالية.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_closing_journal', to='ledger.journal', verbose_name='دفتر إقفال السنة')),
                ('default_manual_journal', models.ForeignKey(blank=True, help_text='يستخدم لأي قيد يُنشأ يدويًا من داخل دفتر الأستاذ.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_default_manual_journal', to='ledger.journal', verbose_name='دفتر القيود اليدوية')),
                ('opening_balance_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود الأرصدة الافتتاحية عند إنشاء أو استيراد رصيد افتتاحي.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_opening_balance_journal', to='ledger.journal', verbose_name='دفتر الرصيد الافتتاحي')),
                ('purchase_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود فواتير الموردين.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_purchase_journal', to='ledger.journal', verbose_name='دفتر المشتريات')),
                ('sales_advance_account', models.ForeignKey(blank=True, help_text='يُستخدم عند استلام دفعة من العميل قبل إصدار الفاتورة.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_advance_account', to='ledger.account', verbose_name='حساب دفعات مقدّمة من العملاء')),
                ('sales_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود فواتير المبيعات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_journal', to='ledger.journal', verbose_name='دفتر المبيعات')),
                ('sales_receivable_account', models.ForeignKey(blank=True, help_text='يُستخدم كطرف مدين عند ترحيل فواتير المبيعات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_receivable_account', to='ledger.account', verbose_name='حساب العملاء (ذمم مدينة)')),
                ('sales_revenue_0_account', models.ForeignKey(blank=True, help_text='إيرادات مبيعات خاضعة للضريبة 0٪ / صادرات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_revenue_0_account', to='ledger.account', verbose_name='حساب المبيعات 0٪')),
                ('sales_vat_output_account', models.ForeignKey(blank=True, help_text='يُستخدم لجزء ضريبة القيمة المضافة على فواتير المبيعات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_vat_output_account', to='ledger.account', verbose_name='حساب ضريبة القيمة المضافة المستحقة (مخرجات)')),
            ],
            options={
                'verbose_name': 'إعدادات دفتر الأستاذ',
                'verbose_name_plural': 'إعدادات دفتر الأستاذ',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='دائن')),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='ledger_line_not_both_debit_credit')],
            },
        ),
    ]
