# Generated by Django 5.2.8 on 2025-11-16 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مقفلة؟')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الدفتر')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدفتر')),
                ('type', models.CharField(choices=[('general', 'دفتر عام'), ('cash', 'دفتر الكاش'), ('bank', 'دفتر البنك'), ('sales', 'دفتر المبيعات'), ('purchase', 'دفتر المشتريات')], default='general', max_length=20, verbose_name='نوع الدفتر')),
                ('is_default', models.BooleanField(default=False, verbose_name='دفتر افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دفتر اليومية',
                'verbose_name_plural': 'دفاتر اليومية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_settlement', models.BooleanField(default=True, help_text='Allow this account to be used in settlements.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='المرجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('number', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='رقم القيد')),
                ('posted', models.BooleanField(default=False, verbose_name='مرحّل')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.fiscalyear', verbose_name='السنة المالية')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.journal', verbose_name='دفتر اليومية')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='مُرحّل بواسطة')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='دائن')),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='ledger_line_not_both_debit_credit')],
            },
        ),
    ]
