# Generated by Django 5.2.8 on 2025-11-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_settlement',
            field=models.BooleanField(default=True, help_text='Allow this account to be used in settlements.'),
        ),
    ]
