# Generated by Django 5.2.8 on 2025-11-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='is_default',
            field=models.BooleanField(default=False, help_text='تُستخدم هذه السنة كافتراضي في التقارير عند عدم اختيار سنة أخرى.', verbose_name='سنة افتراضية للتقارير؟'),
        ),
    ]
