# Generated by Django 5.2.8 on 2025-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_account_allow_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'سنوات مالية',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20),
        ),
    ]
