# Generated by Django 5.2.8 on 2025-11-18 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_fiscalyear_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('bank_journal', models.ForeignKey(blank=True, help_text='يستخدم لحركات حسابات البنك.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_bank_journal', to='ledger.journal', verbose_name='دفتر البنك')),
                ('cash_journal', models.ForeignKey(blank=True, help_text='يستخدم لحركات الصندوق النقدي.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_cash_journal', to='ledger.journal', verbose_name='دفتر الكاش')),
                ('closing_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود إقفال السنة المالية.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_closing_journal', to='ledger.journal', verbose_name='دفتر إقفال السنة')),
                ('default_manual_journal', models.ForeignKey(blank=True, help_text='يستخدم لأي قيد يُنشأ يدويًا من داخل دفتر الأستاذ.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_default_manual_journal', to='ledger.journal', verbose_name='دفتر القيود اليدوية')),
                ('opening_balance_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود الأرصدة الافتتاحية عند إنشاء أو استيراد رصيد افتتاحي.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_opening_balance_journal', to='ledger.journal', verbose_name='دفتر الرصيد الافتتاحي')),
                ('purchase_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود فواتير الموردين.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_purchase_journal', to='ledger.journal', verbose_name='دفتر المشتريات')),
                ('sales_journal', models.ForeignKey(blank=True, help_text='يستخدم لقيود فواتير المبيعات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_journal', to='ledger.journal', verbose_name='دفتر المبيعات')),
            ],
            options={
                'verbose_name': 'إعدادات دفتر الأستاذ',
                'verbose_name_plural': 'إعدادات دفتر الأستاذ',
            },
        ),
    ]
