# Generated by Django 5.2.8 on 2025-11-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_journalentry_posted_at_journalentry_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الدفتر')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدفتر')),
                ('type', models.CharField(choices=[('general', 'دفتر عام'), ('cash', 'دفتر الكاش'), ('bank', 'دفتر البنك'), ('sales', 'دفتر المبيعات'), ('purchase', 'دفتر المشتريات')], default='general', max_length=20, verbose_name='نوع الدفتر')),
                ('is_default', models.BooleanField(default=False, verbose_name='دفتر افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دفتر اليومية',
                'verbose_name_plural': 'دفاتر اليومية',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.journal', verbose_name='دفتر اليومية'),
        ),
    ]
