# Generated by Django 5.2.8 on 2025-11-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_fiscalyear_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.fiscalyear', verbose_name='السنة المالية'),
        ),
    ]
