# Generated by Django 5.2.8 on 2025-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_journal_journalentry_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='رقم القيد'),
        ),
    ]
