# Generated by Django 5.2.8 on 2025-11-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_journalentry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgersettings',
            name='sales_advance_account',
            field=models.ForeignKey(blank=True, help_text='يُستخدم عند استلام دفعة من العميل قبل إصدار الفاتورة.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_advance_account', to='ledger.account', verbose_name='حساب دفعات مقدّمة من العملاء'),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='sales_receivable_account',
            field=models.ForeignKey(blank=True, help_text='يُستخدم كطرف مدين عند ترحيل فواتير المبيعات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_receivable_account', to='ledger.account', verbose_name='حساب العملاء (ذمم مدينة)'),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='sales_revenue_0_account',
            field=models.ForeignKey(blank=True, help_text='إيرادات مبيعات خاضعة للضريبة 0٪ / صادرات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_revenue_0_account', to='ledger.account', verbose_name='حساب المبيعات 0٪'),
        ),
        migrations.AddField(
            model_name='ledgersettings',
            name='sales_vat_output_account',
            field=models.ForeignKey(blank=True, help_text='يُستخدم لجزء ضريبة القيمة المضافة على فواتير المبيعات.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_vat_output_account', to='ledger.account', verbose_name='حساب ضريبة القيمة المضافة المستحقة (مخرجات)'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='fiscalyear_start_before_end'),
        ),
    ]
