# Generated by Django 5.2.8 on 2025-11-16 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_journalentry_fiscal_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-year']},
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='fiscalyear',
            name='date_to',
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ النهاية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البداية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='مقفلة؟'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='مرحّل'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='المرجع'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='دائن'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='مدين'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry', verbose_name='قيد اليومية'),
        ),
    ]
