# Generated by Django 5.2.8 on 2025-11-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('for_operation', models.CharField(choices=[('fixed', 'Fixed'), ('turn', 'Turn (Side Hung)'), ('tilt_turn', 'Tilt & Turn'), ('tilt', 'Tilt Only'), ('door', 'Hinged Door'), ('sliding', 'Sliding')], help_text='This hardware is valid for this operation type.', max_length=20)),
                ('min_height_mm', models.FloatField(default=0)),
                ('max_height_mm', models.FloatField(default=10000)),
                ('min_width_mm', models.FloatField(default=0)),
                ('max_width_mm', models.FloatField(default=10000)),
                ('quantity_per_panel', models.FloatField(default=1.0, help_text='Base quantity per panel (can be scaled by size).')),
                ('depends_on_height', models.BooleanField(default=False)),
                ('depends_on_width', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('frame', 'Outer Frame'), ('sash', 'Sash / Leaf'), ('mullion', 'Mullion'), ('transom', 'Transom')], max_length=20)),
                ('visible_width_mm', models.FloatField(help_text='Visible face width of profile in 2D (mm).')),
                ('depth_mm', models.FloatField(help_text='Profile depth (mm).')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='windowcad.profilesystem')),
            ],
        ),
        migrations.CreateModel(
            name='WindowDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('width_mm', models.FloatField(help_text='Total opening width (mm).')),
                ('height_mm', models.FloatField(help_text='Total opening height (mm).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame_profile', models.ForeignKey(limit_choices_to={'type': 'frame'}, on_delete=django.db.models.deletion.PROTECT, related_name='frame_windows', to='windowcad.profile')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='windowcad.profilesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Left ratio (0–1) in clear opening.')),
                ('y', models.FloatField(help_text='Top ratio (0–1) in clear opening.')),
                ('w', models.FloatField(help_text='Width ratio (0–1) in clear opening.')),
                ('h', models.FloatField(help_text='Height ratio (0–1) in clear opening.')),
                ('type', models.CharField(choices=[('fixed', 'Fixed Glass'), ('window', 'Window Leaf'), ('door', 'Door Leaf')], default='fixed', max_length=20)),
                ('operation', models.CharField(choices=[('fixed', 'Fixed'), ('turn', 'Turn (Side Hung)'), ('tilt_turn', 'Tilt & Turn'), ('tilt', 'Tilt Only'), ('door', 'Hinged Door'), ('sliding', 'Sliding')], default='fixed', help_text='Operation type (turn, tilt-turn, door, etc.).', max_length=20)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='windowcad.windowdesign')),
            ],
        ),
    ]
