# Generated by Django 5.2.8 on 2025-12-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Hardware code / reference.', max_length=50)),
                ('name', models.CharField(help_text='Hardware description.', max_length=255)),
                ('for_operation', models.CharField(choices=[('fixed', 'Fixed'), ('turn', 'Turn (Side Hung)'), ('tilt_turn', 'Tilt & Turn'), ('tilt', 'Tilt Only'), ('door', 'Hinged Door'), ('sliding', 'Sliding')], help_text='Operation type this hardware is valid for.', max_length=20)),
                ('min_height_mm', models.FloatField(default=0, help_text='Minimum panel height (mm) for this hardware.')),
                ('max_height_mm', models.FloatField(default=10000, help_text='Maximum panel height (mm) for this hardware.')),
                ('min_width_mm', models.FloatField(default=0, help_text='Minimum panel width (mm) for this hardware.')),
                ('max_width_mm', models.FloatField(default=10000, help_text='Maximum panel width (mm) for this hardware.')),
                ('quantity_per_panel', models.FloatField(default=1.0, help_text='Base quantity per panel (before scaling by size).')),
                ('depends_on_height', models.BooleanField(default=False, help_text='If true, quantity scales with panel height.')),
                ('depends_on_width', models.BooleanField(default=False, help_text='If true, quantity scales with panel width.')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code of the system, e.g. MZN-46.', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full name/description of the system.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Profile code inside the system.', max_length=50)),
                ('type', models.CharField(choices=[('frame', 'Outer Frame'), ('sash', 'Sash / Leaf'), ('mullion', 'Mullion'), ('transom', 'Transom')], help_text='Profile usage type (frame, sash, mullion, ...).', max_length=20)),
                ('visible_width_mm', models.FloatField(help_text='Visible face width of profile in 2D (mm).')),
                ('depth_mm', models.FloatField(help_text='Profile depth (mm).')),
                ('system', models.ForeignKey(help_text='Parent aluminum system.', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='windowcad.profilesystem')),
            ],
            options={
                'unique_together': {('system', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WindowDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the window/door design (e.g. Living room window).', max_length=200)),
                ('width_mm', models.FloatField(help_text='Total opening width (mm).')),
                ('height_mm', models.FloatField(help_text='Total opening height (mm).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame_profile', models.ForeignKey(help_text='Outer frame profile used for perimeter.', limit_choices_to={'type': 'frame'}, on_delete=django.db.models.deletion.PROTECT, related_name='frame_windows', to='windowcad.profile')),
                ('system', models.ForeignKey(help_text='Aluminum system used for this design.', on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='windowcad.profilesystem')),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Left ratio (0–1) in clear opening.')),
                ('y', models.FloatField(help_text='Top ratio (0–1) in clear opening.')),
                ('w', models.FloatField(help_text='Width ratio (0–1) in clear opening.')),
                ('h', models.FloatField(help_text='Height ratio (0–1) in clear opening.')),
                ('type', models.CharField(choices=[('fixed', 'Fixed Glass'), ('window', 'Window Leaf'), ('door', 'Door Leaf')], default='fixed', help_text='Panel type (fixed, window leaf, door leaf).', max_length=20)),
                ('operation', models.CharField(choices=[('fixed', 'Fixed'), ('turn', 'Turn (Side Hung)'), ('tilt_turn', 'Tilt & Turn'), ('tilt', 'Tilt Only'), ('door', 'Hinged Door'), ('sliding', 'Sliding')], default='fixed', help_text='Operation type (turn, tilt-turn, door, sliding, ...).', max_length=20)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='windowcad.windowdesign')),
            ],
        ),
        migrations.CreateModel(
            name='Mullion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], help_text='Vertical or horizontal mullion.', max_length=10)),
                ('position_ratio', models.FloatField(help_text='Position between 0–1 across the clear opening.')),
                ('profile', models.ForeignKey(blank=True, help_text='Optional specific mullion profile.', limit_choices_to={'type': 'mullion'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mullion_windows', to='windowcad.profile')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mullions', to='windowcad.windowdesign')),
            ],
        ),
    ]
