# Generated by Django 5.2.8 on 2025-11-25 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowcad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mullion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], max_length=10)),
                ('position_ratio', models.FloatField(help_text='Position between 0–1 across the clear opening.')),
                ('profile', models.ForeignKey(blank=True, limit_choices_to={'type': 'mullion'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mullion_windows', to='windowcad.profile')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mullions', to='windowcad.windowdesign')),
            ],
        ),
    ]
