# Generated by Django 5.2.8 on 2025-11-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowcad', '0002_mullion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareitem',
            name='code',
            field=models.CharField(help_text='Hardware code / reference.', max_length=50),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='depends_on_height',
            field=models.BooleanField(default=False, help_text='If true, quantity scales with panel height.'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='depends_on_width',
            field=models.BooleanField(default=False, help_text='If true, quantity scales with panel width.'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='for_operation',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('turn', 'Turn (Side Hung)'), ('tilt_turn', 'Tilt & Turn'), ('tilt', 'Tilt Only'), ('door', 'Hinged Door'), ('sliding', 'Sliding')], help_text='Operation type this hardware is valid for.', max_length=20),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='max_height_mm',
            field=models.FloatField(default=10000, help_text='Maximum panel height (mm) for this hardware.'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='max_width_mm',
            field=models.FloatField(default=10000, help_text='Maximum panel width (mm) for this hardware.'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='min_height_mm',
            field=models.FloatField(default=0, help_text='Minimum panel height (mm) for this hardware.'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='min_width_mm',
            field=models.FloatField(default=0, help_text='Minimum panel width (mm) for this hardware.'),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='name',
            field=models.CharField(help_text='Hardware description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='hardwareitem',
            name='quantity_per_panel',
            field=models.FloatField(default=1.0, help_text='Base quantity per panel (before scaling by size).'),
        ),
        migrations.AlterField(
            model_name='mullion',
            name='orientation',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], help_text='Vertical or horizontal mullion.', max_length=10),
        ),
        migrations.AlterField(
            model_name='mullion',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Optional specific mullion profile.', limit_choices_to={'type': 'mullion'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mullion_windows', to='windowcad.profile'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='operation',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('turn', 'Turn (Side Hung)'), ('tilt_turn', 'Tilt & Turn'), ('tilt', 'Tilt Only'), ('door', 'Hinged Door'), ('sliding', 'Sliding')], default='fixed', help_text='Operation type (turn, tilt-turn, door, sliding, ...).', max_length=20),
        ),
        migrations.AlterField(
            model_name='panel',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed Glass'), ('window', 'Window Leaf'), ('door', 'Door Leaf')], default='fixed', help_text='Panel type (fixed, window leaf, door leaf).', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(help_text='Profile code inside the system.', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='system',
            field=models.ForeignKey(help_text='Parent aluminum system.', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='windowcad.profilesystem'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('frame', 'Outer Frame'), ('sash', 'Sash / Leaf'), ('mullion', 'Mullion'), ('transom', 'Transom')], help_text='Profile usage type (frame, sash, mullion, ...).', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilesystem',
            name='code',
            field=models.CharField(help_text='Short code of the system, e.g. MZN-46.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profilesystem',
            name='name',
            field=models.CharField(help_text='Full name/description of the system.', max_length=200),
        ),
        migrations.AlterField(
            model_name='windowdesign',
            name='frame_profile',
            field=models.ForeignKey(help_text='Outer frame profile used for perimeter.', limit_choices_to={'type': 'frame'}, on_delete=django.db.models.deletion.PROTECT, related_name='frame_windows', to='windowcad.profile'),
        ),
        migrations.AlterField(
            model_name='windowdesign',
            name='name',
            field=models.CharField(help_text='Name of the window/door design (e.g. Living room window).', max_length=200),
        ),
        migrations.AlterField(
            model_name='windowdesign',
            name='system',
            field=models.ForeignKey(help_text='Aluminum system used for this design.', on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='windowcad.profilesystem'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('system', 'code')},
        ),
    ]
