# Generated by Django 5.2.8 on 2025-11-27 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0005_paymentmethod_payment_paymentallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب البنكي')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='اسم البنك')),
                ('iban', models.CharField(blank=True, max_length=64, verbose_name='IBAN')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='رقم الحساب')),
                ('currency', models.CharField(default='OMR', max_length=10, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounting.account', verbose_name='الحساب المحاسبي')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='من تاريخ')),
                ('date_to', models.DateField(verbose_name='إلى تاريخ')),
                ('opening_balance', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='الرصيد الافتتاحي')),
                ('closing_balance', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='الرصيد الختامي')),
                ('imported_file', models.FileField(blank=True, null=True, upload_to='bank_statements/', verbose_name='ملف الكشف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد التسوية'), ('reconciled', 'مُسوّى')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='banking.bankaccount', verbose_name='الحساب البنكي')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('reference', models.CharField(blank=True, max_length=128, verbose_name='المرجع')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='المبلغ (+/-)')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='الرصيد بعد الحركة')),
                ('match_status', models.CharField(choices=[('unmatched', 'غير مُسوّى'), ('partial', 'مسوى جزئياً'), ('matched', 'مسوى بالكامل')], default='unmatched', max_length=20, verbose_name='حالة التسوية')),
                ('external_id', models.CharField(blank=True, max_length=128, verbose_name='معرّف البنك')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_lines', to='accounting.journalentry', verbose_name='قيد اليومية')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_lines', to='accounting.payment', verbose_name='سند دفع/قبض')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.bankstatement', verbose_name='كشف البنك')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
