# Generated by Django 5.2.8 on 2025-11-29 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: بنك مسقط - جاري 1234', max_length=255, verbose_name='اسم الحساب البنكي')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='اسم البنك')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=64, verbose_name='IBAN')),
                ('currency', models.CharField(default='OMR', max_length=10, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('account', models.OneToOneField(help_text='الحساب في دليل الحسابات الذي ستتم عليه القيود', on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_config', to='accounting.account', verbose_name='الحساب المحاسبي (GL)')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'حسابات بنكية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: كشف يناير 2024', max_length=255, verbose_name='مرجع الكشف')),
                ('date', models.DateField(db_index=True, verbose_name='تاريخ الكشف')),
                ('start_balance', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='الرصيد الافتتاحي')),
                ('end_balance', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='الرصيد الختامي')),
                ('imported_file', models.FileField(blank=True, null=True, upload_to='bank_statements/', verbose_name='ملف الكشف (Excel/PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='banking.bankaccount', verbose_name='الحساب البنكي')),
            ],
            options={
                'verbose_name': 'كشف حساب',
                'verbose_name_plural': 'كشوفات الحساب',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('label', models.CharField(max_length=255, verbose_name='البيان/الوصف')),
                ('ref', models.CharField(blank=True, max_length=100, verbose_name='المرجع البنكي')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='المبلغ')),
                ('amount_residual', models.DecimalField(decimal_places=3, editable=False, max_digits=18, verbose_name='المتبقي للتسوية')),
                ('is_reconciled', models.BooleanField(default=False, editable=False, verbose_name='مُسوّى بالكامل')),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشريك المقترح')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.bankstatement', verbose_name='الكشف التابع له')),
            ],
            options={
                'verbose_name': 'حركة بنكية',
                'verbose_name_plural': 'حركات بنكية',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_reconciled', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='المبلغ المُسوّى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسوية')),
                ('journal_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliations', to='accounting.journalline', verbose_name='سطر القيد المحاسبي')),
                ('bank_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='banking.bankstatementline', verbose_name='حركة البنك')),
            ],
            options={
                'verbose_name': 'تسوية',
                'verbose_name_plural': 'سجل التسويات',
            },
        ),
    ]
