# Generated by Django 5.2.8 on 2025-11-23 10:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. STOCK, SCRAP, SHOWROOM.', max_length=30, verbose_name='Location code')),
                ('name', models.CharField(max_length=200, verbose_name='Location name')),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('scrap', 'Scrap'), ('transit', 'Transit')], default='internal', max_length=20, verbose_name='Location type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Stock location',
                'verbose_name_plural': 'Stock locations',
                'ordering': ('warehouse__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. WH-MCT.', max_length=20, unique=True, verbose_name='Warehouse code')),
                ('name', models.CharField(max_length=200, verbose_name='Warehouse name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. mazoon-46-system', max_length=120, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Category name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productcategory', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Internal code / SKU, e.g. MZN-46-FRAME.', max_length=50, unique=True, verbose_name='Product code')),
                ('name', models.CharField(max_length=255, verbose_name='Product name')),
                ('short_description', models.CharField(blank=True, help_text='One-line description shown in lists.', max_length=255, verbose_name='Short description')),
                ('description', models.TextField(blank=True, verbose_name='Full description')),
                ('uom', models.CharField(default='PCS', help_text='Example: PCS, M, KG, SET.', max_length=20, verbose_name='Unit of measure')),
                ('is_stock_item', models.BooleanField(default=True, help_text='If disabled, stock will not be tracked for this product.', verbose_name='Stock item')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, product is not used in new documents.', verbose_name='Active')),
                ('is_published', models.BooleanField(default=False, help_text='If enabled, product can appear on website / portal.', verbose_name='Published')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('move_type', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing'), ('transfer', 'Transfer')], default='in', max_length=20, verbose_name='Move type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('uom', models.CharField(help_text='Usually copied from product.uom.', max_length=20, verbose_name='Unit of measure')),
                ('move_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Move date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(blank=True, help_text='Optional external reference, e.g. PO/2025/0001.', max_length=255, verbose_name='Reference')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.stocklocation', verbose_name='From location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product', verbose_name='Product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.stocklocation', verbose_name='To location')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.warehouse', verbose_name='From warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.warehouse', verbose_name='To warehouse')),
            ],
            options={
                'verbose_name': 'Stock move',
                'verbose_name_plural': 'Stock moves',
                'ordering': ('-move_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Quantity on hand')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Reserved quantity')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Minimum stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.product', verbose_name='Product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.stocklocation', verbose_name='Location inside warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock level',
                'verbose_name_plural': 'Stock levels',
                'unique_together': {('product', 'warehouse', 'location')},
            },
        ),
    ]
