# Generated by Django 5.2.8 on 2025-11-24 15:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_move_in_prefix', models.CharField(default='IN', max_length=10, verbose_name='بادئة الحركات الواردة (IN)')),
                ('stock_move_out_prefix', models.CharField(default='OUT', max_length=10, verbose_name='بادئة الحركات الصادرة (OUT)')),
                ('stock_move_transfer_prefix', models.CharField(default='TRF', max_length=10, verbose_name='بادئة حركات التحويل (TRANSFER)')),
            ],
            options={
                'verbose_name': 'إعدادات المخزون',
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. STOCK, SCRAP, SHOWROOM.', max_length=30, verbose_name='Location code')),
                ('name', models.CharField(max_length=200, verbose_name='Location name')),
                ('type', models.CharField(choices=[('internal', 'Internal'), ('supplier', 'Supplier'), ('customer', 'Customer'), ('scrap', 'Scrap'), ('transit', 'Transit')], default='internal', max_length=20, verbose_name='Location type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Stock location',
                'verbose_name_plural': 'Stock locations',
                'ordering': ('warehouse__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. WH-MCT.', max_length=20, unique=True, verbose_name='Warehouse code')),
                ('name', models.CharField(max_length=200, verbose_name='Warehouse name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='معرّف يصلح للرابط بدون مسافات، مثل: mazoon-46-system', max_length=120, unique=True, verbose_name='المعرّف (Slug)')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productcategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف منتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='كود داخلي فريد، مثل: MZN-46-FRAME', max_length=50, unique=True, verbose_name='كود المنتج')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('short_description', models.CharField(blank=True, help_text='سطر واحد يظهر في القوائم والجداول.', max_length=255, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, verbose_name='وصف تفصيلي')),
                ('alt_factor', models.DecimalField(blank=True, decimal_places=6, help_text='كم تساوي 1 وحدة بديلة من الوحدة الأساسية. مثال: إذا الأساس متر والبديلة لفة 6م، اكتب 6.', max_digits=18, null=True, verbose_name='عامل تحويل الوحدة البديلة')),
                ('weight_per_base', models.DecimalField(blank=True, decimal_places=6, help_text='الوزن في وحدة الوزن لكل 1 من الوحدة الأساسية. مثال: إذا الأساس متر ووحدة الوزن كجم، هذا الحقل هو كجم/م.', max_digits=18, null=True, verbose_name='الوزن لكل وحدة أساسية')),
                ('is_stock_item', models.BooleanField(default=True, help_text='إذا تم تعطيله، لن يتم تتبع هذا المنتج في حركات المخزون.', verbose_name='يُتابَع في المخزون')),
                ('is_active', models.BooleanField(default=True, help_text='إذا تم تعطيله، لن يظهر في المستندات الجديدة.', verbose_name='نشط')),
                ('is_published', models.BooleanField(default=False, help_text='إذا تم تفعيله، يمكن عرض المنتج في الموقع أو بوابة العملاء.', verbose_name='منشور على الموقع/البوابة')),
                ('alt_uom', models.ForeignKey(blank=True, help_text='وحدة أخرى للبيع أو الشراء (مثل: لفة، كرتون). سيتم تعريف 1 وحدة بديلة كـ alt_factor من الوحدة الأساسية.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_alt', to='uom.unitofmeasure', verbose_name='وحدة بديلة')),
                ('base_uom', models.ForeignKey(help_text='الوحدة الأساسية للمخزون، مثل: M, PCS.', on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base', to='uom.unitofmeasure', verbose_name='وحدة القياس الأساسية')),
                ('weight_uom', models.ForeignKey(blank=True, help_text='الوحدة المستخدمة للوزن، مثل: KG.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_weight', to='uom.unitofmeasure', verbose_name='وحدة الوزن')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=64, unique=True, verbose_name='رقم')),
                ('move_type', models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing'), ('transfer', 'Transfer')], default='in', max_length=20, verbose_name='Move type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('move_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Move date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(blank=True, help_text='Optional external reference, e.g. PO/2025/0001.', max_length=255, verbose_name='Reference')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.stocklocation', verbose_name='From location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product', verbose_name='Product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.stocklocation', verbose_name='To location')),
                ('uom', models.ForeignKey(blank=True, help_text='Unit of measure used for this move (must be base or alternative UoM of the product).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='uom.unitofmeasure', verbose_name='Unit of measure')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.warehouse', verbose_name='From warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.warehouse', verbose_name='To warehouse')),
            ],
            options={
                'verbose_name': 'Stock move',
                'verbose_name_plural': 'Stock moves',
                'ordering': ('-move_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Quantity on hand')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Reserved quantity')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Minimum stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.product', verbose_name='Product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.stocklocation', verbose_name='Location inside warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock level',
                'verbose_name_plural': 'Stock levels',
                'unique_together': {('product', 'warehouse', 'location')},
            },
        ),
    ]
