# Generated by Django 5.2.8 on 2025-12-01 13:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_move_in_prefix', models.CharField(default='IN', max_length=10, verbose_name='بادئة الحركات الواردة (IN)')),
                ('stock_move_out_prefix', models.CharField(default='OUT', max_length=10, verbose_name='بادئة الحركات الصادرة (OUT)')),
                ('stock_move_transfer_prefix', models.CharField(default='TRF', max_length=10, verbose_name='بادئة حركات التحويل (TRANSFER)')),
            ],
            options={
                'verbose_name': 'إعدادات المخزون',
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(help_text='كود قصير، مثل: STOCK, SCRAP, SHOWROOM.', max_length=30, verbose_name='كود الموقع')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('type', models.CharField(choices=[('internal', 'داخلي'), ('supplier', 'مورد'), ('customer', 'عميل'), ('scrap', 'تالفة'), ('transit', 'قيد النقل')], default='internal', max_length=20, verbose_name='نوع الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موقع مخزون',
                'verbose_name_plural': 'مواقع المخزون',
                'ordering': ('warehouse__code', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(help_text='كود قصير، مثل: WH-MCT.', max_length=20, unique=True, verbose_name='كود المستودع')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المستودع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('slug', models.SlugField(help_text='معرّف يصلح للرابط بدون مسافات، مثل: mazoon-46-system', max_length=120, unique=True, verbose_name='المعرّف (Slug)')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.productcategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف منتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('code', models.CharField(help_text='كود داخلي فريد، مثل: MZN-46-FRAME', max_length=50, unique=True, verbose_name='كود المنتج')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('default_sale_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='سعر البيع الداخلي الافتراضي لكل وحدة القياس الأساسية للمنتج.', max_digits=12, verbose_name='سعر البيع الافتراضي (لكل وحدة أساس)')),
                ('default_cost_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يُستخدم للتقارير الداخلية وتقدير تكلفة المخزون (اختياري).', max_digits=12, verbose_name='سعر التكلفة التقريبي')),
                ('short_description', models.CharField(blank=True, help_text='سطر واحد يظهر في القوائم والجداول.', max_length=255, verbose_name='وصف مختصر')),
                ('description', models.TextField(blank=True, verbose_name='وصف تفصيلي')),
                ('product_type', models.CharField(choices=[('stockable', 'صنف مخزني'), ('service', 'خدمة'), ('consumable', 'مستهلكات')], default='stockable', help_text='يحدد إذا كان المنتج مخزني، خدمة أو مستهلكات.', max_length=20, verbose_name='نوع المنتج')),
                ('alt_factor', models.DecimalField(blank=True, decimal_places=6, help_text='كم تساوي 1 وحدة بديلة من الوحدة الأساسية. مثال: إذا الأساس متر والبديلة لفة 6م، اكتب 6.', max_digits=18, null=True, verbose_name='عامل تحويل الوحدة البديلة')),
                ('weight_per_base', models.DecimalField(blank=True, decimal_places=6, help_text='الوزن في وحدة الوزن لكل 1 من الوحدة الأساسية. مثال: إذا الأساس متر ووحدة الوزن كجم، هذا الحقل هو كجم/م.', max_digits=18, null=True, verbose_name='الوزن لكل وحدة أساسية')),
                ('is_stock_item', models.BooleanField(default=True, help_text='إذا تم تعطيله، لن يتم تتبع هذا المنتج في حركات المخزون.', verbose_name='يُتابَع في المخزون')),
                ('is_active', models.BooleanField(default=True, help_text='إذا تم تعطيله، لن يظهر في المستندات الجديدة.', verbose_name='نشط')),
                ('is_published', models.BooleanField(default=False, help_text='إذا تم تفعيله، يمكن عرض المنتج في الموقع أو بوابة العملاء.', verbose_name='منشور على الموقع/البوابة')),
                ('alt_uom', models.ForeignKey(blank=True, help_text='وحدة أخرى للبيع أو الشراء (مثل: لفة، كرتون). سيتم تعريف 1 وحدة بديلة كـ alt_factor من الوحدة الأساسية.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_alt', to='uom.unitofmeasure', verbose_name='وحدة بديلة')),
                ('base_uom', models.ForeignKey(help_text='الوحدة الأساسية للمخزون، مثل: م، قطعة.', on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base', to='uom.unitofmeasure', verbose_name='وحدة القياس الأساسية')),
                ('weight_uom', models.ForeignKey(blank=True, help_text='الوحدة المستخدمة للوزن، مثل: كجم.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_weight', to='uom.unitofmeasure', verbose_name='وحدة الوزن')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('move_type', models.CharField(choices=[('in', 'حركة واردة'), ('out', 'حركة صادرة'), ('transfer', 'تحويل بين مواقع/مستودعات')], default='in', max_length=20, verbose_name='نوع الحركة')),
                ('move_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('done', 'منفذة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('reference', models.CharField(blank=True, help_text='مرجع خارجي اختياري، مثل: PO/2025/0001.', max_length=255, verbose_name='مرجع خارجي')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.stocklocation', verbose_name='من موقع')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.stocklocation', verbose_name='إلى موقع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.warehouse', verbose_name='من مستودع')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.warehouse', verbose_name='إلى مستودع')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ('-move_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmove', verbose_name='حركة المخزون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product', verbose_name='المنتج')),
                ('uom', models.ForeignKey(help_text='وحدة القياس المستخدمة في هذا السطر ويجب أن تكون وحدة الأساس أو الوحدة البديلة للمنتج.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_move_lines', to='uom.unitofmeasure', verbose_name='وحدة القياس')),
            ],
            options={
                'verbose_name': 'بند حركة مخزون',
                'verbose_name_plural': 'بنود حركات المخزون',
            },
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='المستودع'),
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الكمية المتوفرة')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='كمية محجوزة')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الحد الأدنى للمخزون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.product', verbose_name='المنتج')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.stocklocation', verbose_name='الموقع داخل المستودع')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'رصيد مخزون',
                'verbose_name_plural': 'أرصدة المخزون',
            },
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_date', 'status'], name='stockmove_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['status'], name='stockmove_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse__isnull', False), ('to_warehouse__isnull', False), ('from_location__isnull', False), ('to_location__isnull', False), ('from_warehouse', models.F('to_warehouse')), ('from_location', models.F('to_location')), _negated=True), name='stockmove_from_to_not_same'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['product', 'warehouse'], name='stk_lvl_prod_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['warehouse', 'location'], name='stk_lvl_wh_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stocklevel_quantity_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='stocklevel_quantity_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='stocklevel_min_stock_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'warehouse', 'location')},
        ),
    ]
