# Generated by Django 5.2.8 on 2025-11-29 12:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'verbose_name': 'رصيد مخزون', 'verbose_name_plural': 'أرصدة المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'ordering': ('warehouse__code', 'code'), 'verbose_name': 'موقع مخزون', 'verbose_name_plural': 'مواقع المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stockmove',
            options={'ordering': ('-move_date', '-id'), 'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stockmoveline',
            options={'verbose_name': 'بند حركة مخزون', 'verbose_name_plural': 'بنود حركات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('code',), 'verbose_name': 'مستودع', 'verbose_name_plural': 'المستودعات'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stockable', 'صنف مخزني'), ('service', 'خدمة'), ('consumable', 'مستهلكات')], default='stockable', help_text='يحدد إذا كان المنتج مخزني، خدمة أو مستهلكات.', max_length=20, verbose_name='نوع المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(help_text='الوحدة الأساسية للمخزون، مثل: م، قطعة.', on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base', to='uom.unitofmeasure', verbose_name='وحدة القياس الأساسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_cost_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يُستخدم للتقارير الداخلية وتقدير تكلفة المخزون (اختياري).', max_digits=12, verbose_name='سعر التكلفة التقريبي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_uom',
            field=models.ForeignKey(blank=True, help_text='الوحدة المستخدمة للوزن، مثل: كجم.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_weight', to='uom.unitofmeasure', verbose_name='وحدة الوزن'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.stocklocation', verbose_name='الموقع داخل المستودع'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الحد الأدنى للمخزون'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الكمية المتوفرة'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='كمية محجوزة'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse', verbose_name='المستودع'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='code',
            field=models.CharField(help_text='كود قصير، مثل: STOCK, SCRAP, SHOWROOM.', max_length=30, verbose_name='كود الموقع'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الموقع'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='type',
            field=models.CharField(choices=[('internal', 'داخلي'), ('supplier', 'مورد'), ('customer', 'عميل'), ('scrap', 'تالفة'), ('transit', 'قيد النقل')], default='internal', max_length=20, verbose_name='نوع الموقع'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='المستودع'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.stocklocation', verbose_name='من موقع'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_moves', to='inventory.warehouse', verbose_name='من مستودع'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='move_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('in', 'حركة واردة'), ('out', 'حركة صادرة'), ('transfer', 'تحويل بين مواقع/مستودعات')], default='in', max_length=20, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='note',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='reference',
            field=models.CharField(blank=True, help_text='مرجع خارجي اختياري، مثل: PO/2025/0001.', max_length=255, verbose_name='مرجع خارجي'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('done', 'منفذة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.stocklocation', verbose_name='إلى موقع'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_moves', to='inventory.warehouse', verbose_name='إلى مستودع'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmove', verbose_name='حركة المخزون'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='uom',
            field=models.ForeignKey(help_text='وحدة القياس المستخدمة في هذا السطر ويجب أن تكون وحدة الأساس أو الوحدة البديلة للمنتج.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_move_lines', to='uom.unitofmeasure', verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(help_text='كود قصير، مثل: WH-MCT.', max_length=20, unique=True, verbose_name='كود المستودع'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المستودع'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['product', 'warehouse'], name='stk_lvl_prod_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['warehouse', 'location'], name='stk_lvl_wh_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_date', 'status'], name='stockmove_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['status'], name='stockmove_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stocklevel_quantity_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='stocklevel_quantity_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__gte', 0)), name='stocklevel_min_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.CheckConstraint(condition=models.Q(('from_warehouse__isnull', False), ('to_warehouse__isnull', False), ('from_location__isnull', False), ('to_location__isnull', False), ('from_warehouse', models.F('to_warehouse')), ('from_location', models.F('to_location')), _negated=True), name='stockmove_from_to_not_same'),
        ),
    ]
