# Generated by Django 5.2.8 on 2025-12-10 13:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory', verbose_name='نطاق التصنيف'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklocation', verbose_name='نطاق الموقع'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد المراجعة'), ('applied', 'تم الترحيل'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentline',
            name='counted_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='الكمية الفعلية'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentline',
            name='theoretical_qty',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية النظرية'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='stock_move_in_prefix',
            field=models.CharField(default='IN', max_length=10, verbose_name='بادئة الحركات الواردة'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='stock_move_out_prefix',
            field=models.CharField(default='OUT', max_length=10, verbose_name='بادئة الحركات الصادرة'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='stock_move_transfer_prefix',
            field=models.CharField(default='TRF', max_length=10, verbose_name='بادئة التحويلات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يتم تحديثه تلقائياً عند التوريد.', max_digits=12, verbose_name='متوسط التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود المنتج (SKU)'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, verbose_name='مدة التوريد (أيام)'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='inventory.stocklocation', verbose_name='الموقع (اختياري)'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='min_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الحد الأدنى'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='multiple_of',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='مضاعفات الكمية'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='target_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الكمية المستهدفة'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الحد الأدنى (Legacy)'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='inventory.inventoryadjustment', verbose_name='وثيقة الجرد المرتبطة'),
        ),
    ]
