# Generated by Django 5.2.8 on 2025-11-24 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmove',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='uom',
        ),
        migrations.CreateModel(
            name='StockMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantity')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmove', verbose_name='Stock move')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='inventory.product', verbose_name='Product')),
                ('uom', models.ForeignKey(help_text='Unit of measure used for this line (must be base or alternative UoM of the product).', on_delete=django.db.models.deletion.PROTECT, related_name='stock_move_lines', to='uom.unitofmeasure', verbose_name='Unit of measure')),
            ],
            options={
                'verbose_name': 'Stock move line',
                'verbose_name_plural': 'Stock move lines',
            },
        ),
    ]
