# Generated by Django 5.2.8 on 2025-12-10 13:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryadjustment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='category',
            field=models.ForeignKey(blank=True, help_text='اختياري: لجرد قسم معين فقط.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory', verbose_name='نطاق التصنيف'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='اختياري: لجرد رف/موقع معين فقط.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklocation', verbose_name='نطاق الموقع'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة / قيد العد'), ('in_progress', 'قيد المراجعة'), ('applied', 'تم الترحيل'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentline',
            name='counted_qty',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='ما تم عده فعلياً. اتركه فارغاً إذا لم يتم العد بعد.', max_digits=12, null=True, verbose_name='الكمية الفعلية (العد)'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentline',
            name='theoretical_qty',
            field=models.DecimalField(decimal_places=3, help_text='الرصيد المسجل في النظام لحظة إنشاء الوثيقة.', max_digits=12, verbose_name='الكمية النظرية (النظام)'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='stock_move_in_prefix',
            field=models.CharField(default='IN', max_length=10, verbose_name='بادئة الحركات الواردة (IN)'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='stock_move_out_prefix',
            field=models.CharField(default='OUT', max_length=10, verbose_name='بادئة الحركات الصادرة (OUT)'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='stock_move_transfer_prefix',
            field=models.CharField(default='TRF', max_length=10, verbose_name='بادئة حركات التحويل (TRANSFER)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يتم تحديثه تلقائياً عند التوريد بناءً على المتوسط المرجح.', max_digits=12, verbose_name='متوسط التكلفة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13, UPC, أو أي رمز شريطي.', max_length=100, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='كود داخلي فريد.', max_length=50, unique=True, verbose_name='كود المنتج (SKU)'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='اختياري: عدد الأيام التقريبية لوصول البضاعة بعد الطلب.', verbose_name='مدة التوريد (أيام)'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='location',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً لتطبيق القاعدة على مستوى المستودع بالكامل.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='inventory.stocklocation', verbose_name='الموقع داخل المستودع (اختياري)'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='min_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='عند نزول الرصيد عن هذه الكمية، يظهر تنبيه إعادة الطلب.', max_digits=12, verbose_name='الحد الأدنى'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='multiple_of',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='اختياري: إن كان يجب الطلب دائماً بمضاعفات معينة (مثال: بار بطول 6م، تكتب 6).', max_digits=12, null=True, verbose_name='مضاعفات الكمية'),
        ),
        migrations.AlterField(
            model_name='reorderrule',
            name='target_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='الكمية التي تود الوصول إليها بعد الشراء/التوريد. يُستخدم لحساب الكمية المقترحة للطلب.', max_digits=12, verbose_name='الكمية المستهدفة'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يفضل استخدام قواعد إعادة الطلب بدلاً من هذا الحقل.', max_digits=12, verbose_name='الحد الأدنى (Legacy)'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='adjustment',
            field=models.ForeignKey(blank=True, help_text='يتم تعبئته آلياً إذا كانت الحركة ناتجة عن تسوية جردية.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='inventory.inventoryadjustment', verbose_name='وثيقة الجرد المرتبطة'),
        ),
    ]
