# Generated by Django 5.2.8 on 2025-11-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmove_uom'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Unit of measure used for this move (must be base or alternative UoM of the product).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='uom.unitofmeasure', verbose_name='Unit of measure'),
        ),
    ]
