# Generated by Django 5.2.8 on 2025-12-09 13:57

import django.db.models.deletion
import django.utils.timezone
import inventory.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_product_code_idx_product_product_active_idx_and_more'),
        ('uom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('min_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='عند نزول الرصيد عن هذه الكمية، يظهر تنبيه إعادة الطلب.', max_digits=12, verbose_name='الحد الأدنى')),
                ('target_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='الكمية التي تود الوصول إليها بعد الشراء/التوريد. يُستخدم لحساب الكمية المقترحة للطلب.', max_digits=12, verbose_name='الكمية المستهدفة')),
                ('multiple_of', models.DecimalField(blank=True, decimal_places=3, help_text='اختياري: إن كان يجب الطلب دائماً بمضاعفات معينة (مثال: بار بطول 6م، تكتب 6).', max_digits=12, null=True, verbose_name='مضاعفات الكمية')),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='اختياري: عدد الأيام التقريبية لوصول البضاعة بعد الطلب.', verbose_name='مدة التوريد (أيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'قاعدة إعادة طلب',
                'verbose_name_plural': 'قواعد إعادة الطلب',
            },
        ),
        migrations.AlterModelOptions(
            name='stockmoveline',
            options={'verbose_name': 'بند حركة', 'verbose_name_plural': 'بنود الحركة'},
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='stocklevel_quantity_on_hand_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='stocklevel_quantity_reserved_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='stocklevel_min_stock_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='stockmove',
            name='stockmove_from_to_not_same',
        ),
        migrations.RemoveIndex(
            model_name='stocklevel',
            name='stk_lvl_prod_wh_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklevel',
            name='stk_lvl_wh_loc_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklocation',
            name='stockloc_wh_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklocation',
            name='stockloc_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmove',
            name='stockmove_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmove',
            name='stockmove_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouse',
            name='wh_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouse',
            name='wh_active_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_cost_price',
        ),
        migrations.AddField(
            model_name='inventorysettings',
            name='allow_negative_stock',
            field=models.BooleanField(default=True, help_text='إذا تم تفعيله، يمكن للمستخدمين تأكيد حركات صرف حتى لو لم تتوفر كمية كافية.', verbose_name='السماح بالمخزون السالب'),
        ),
        migrations.AddField(
            model_name='product',
            name='average_cost',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يتم تحديثه تلقائياً عند التوريد بناءً على المتوسط المرجح.', max_digits=12, verbose_name='متوسط التكلفة'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13, UPC, أو أي رمز شريطي.', max_length=100, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.AddField(
            model_name='stockmoveline',
            name='cost_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='تكلفة الوحدة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt_factor',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='كم تساوي 1 وحدة بديلة من الوحدة الأساسية.', max_digits=18, null=True, verbose_name='عامل التحويل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alt_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_alt', to='uom.unitofmeasure', verbose_name='وحدة بديلة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_as_base', to='uom.unitofmeasure', verbose_name='وحدة القياس الأساسية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='كود داخلي فريد.', max_length=50, unique=True, verbose_name='كود المنتج (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_sale_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='سعر البيع الافتراضي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_upload_to, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منشور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_stock_item',
            field=models.BooleanField(default=True, verbose_name='يُتابَع في المخزون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stockable', 'صنف مخزني'), ('service', 'خدمة'), ('consumable', 'مستهلكات')], default='stockable', max_length=20, verbose_name='نوع المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_per_base',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='الوزن لكل وحدة أساس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_as_weight', to='uom.unitofmeasure', verbose_name='وحدة الوزن'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='المعرّف (Slug)'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.stocklocation', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يفضل استخدام قواعد إعادة الطلب بدلاً من هذا الحقل.', max_digits=12, verbose_name='الحد الأدنى (Legacy)'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الكمية المحجوزة'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='code',
            field=models.CharField(max_length=30, verbose_name='كود الموقع'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('in', 'حركة واردة'), ('out', 'حركة صادرة'), ('transfer', 'تحويل داخلي')], default='in', max_length=20, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='مرجع خارجي'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockmove', verbose_name='الحركة'),
        ),
        migrations.AlterField(
            model_name='stockmoveline',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure', verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود المستودع'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['product', 'warehouse', 'location'], name='stocklevel_prod_wh_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__gte', 0)), name='stocklevel_reserved_non_negative'),
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='location',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً لتطبيق القاعدة على مستوى المستودع بالكامل.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='inventory.stocklocation', verbose_name='الموقع داخل المستودع (اختياري)'),
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AddField(
            model_name='reorderrule',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_rules', to='inventory.warehouse', verbose_name='المستودع'),
        ),
        migrations.AddIndex(
            model_name='reorderrule',
            index=models.Index(fields=['product', 'warehouse'], name='reorder_prod_wh_idx'),
        ),
        migrations.AddConstraint(
            model_name='reorderrule',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'location'), name='uniq_reorder_rule_per_product_wh_loc'),
        ),
    ]
