# Generated by Django 5.2.8 on 2025-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stockmove_product_remove_stockmove_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_cost_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='يستخدم للتقارير الداخلية وتقدير تكلفة المخزون (اختياري).', max_digits=12, verbose_name='سعر التكلفة التقريبي'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_sale_price',
            field=models.DecimalField(decimal_places=3, default=0, help_text='سعر البيع الداخلي الافتراضي لكل وحدة القياس الأساسية للمنتج.', max_digits=12, verbose_name='سعر البيع الافتراضي (لكل وحدة أساس)'),
        ),
    ]
