# Generated by Django 5.2.8 on 2025-12-09 15:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_reorderrule_alter_stockmoveline_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الجرد')),
                ('status', models.CharField(choices=[('draft', 'مسودة / قيد العد'), ('in_progress', 'قيد المراجعة'), ('applied', 'تم الترحيل'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('category', models.ForeignKey(blank=True, help_text='اختياري: لجرد قسم معين فقط.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory', verbose_name='نطاق التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('location', models.ForeignKey(blank=True, help_text='اختياري: لجرد رف/موقع معين فقط.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocklocation', verbose_name='نطاق الموقع')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'وثيقة جرد',
                'verbose_name_plural': 'وثائق الجرد',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='stockmove',
            name='adjustment',
            field=models.ForeignKey(blank=True, help_text='يتم تعبئته آلياً إذا كانت الحركة ناتجة عن تسوية جردية.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='inventory.inventoryadjustment', verbose_name='وثيقة الجرد المرتبطة'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('theoretical_qty', models.DecimalField(decimal_places=3, help_text='الرصيد المسجل في النظام لحظة إنشاء الوثيقة.', max_digits=12, verbose_name='الكمية النظرية (النظام)')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=3, help_text='ما تم عده فعلياً. اتركه فارغاً إذا لم يتم العد بعد.', max_digits=12, null=True, verbose_name='الكمية الفعلية (العد)')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryadjustment', verbose_name='وثيقة الجرد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklocation', verbose_name='الموقع المحدد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'بند جرد',
                'verbose_name_plural': 'بنود الجرد',
                'unique_together': {('adjustment', 'product', 'location')},
            },
        ),
    ]
