# Generated by Django 5.2.8 on 2025-12-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryadjustment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_stock_item',
        ),
    ]
