# Generated by Django 5.2.8 on 2025-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryadjustment_stockmove_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='note_ar',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='note_en',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف تفصيلي'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف تفصيلي'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف مختصر'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف مختصر'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف التصنيف'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='وصف التصنيف'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم التصنيف'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم التصنيف'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم الموقع'),
        ),
        migrations.AddField(
            model_name='stocklocation',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم الموقع'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='note_ar',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='stockmove',
            name='note_en',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم المستودع'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='اسم المستودع'),
        ),
    ]
