# Generated by Django 5.2.8 on 2025-12-13 16:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_is_stock_item'),
        ('uom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryadjustmentline',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stocklocation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الجرد'),
        ),
        migrations.AlterField(
            model_name='inventorysettings',
            name='allow_negative_stock',
            field=models.BooleanField(default=True, help_text='إذا تم تفعيله، يمكن تأكيد حركات الصرف حتى لو لم تتوفر كمية كافية.', verbose_name='السماح بالمخزون السالب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الباركود'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['warehouse', 'date'], name='invadj_wh_date_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['status'], name='invadj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentline',
            index=models.Index(fields=['adjustment'], name='invadjline_adj_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentline',
            index=models.Index(fields=['product'], name='invadjline_product_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='product_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent'], name='prodcat_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderrule',
            index=models.Index(fields=['is_active'], name='reorder_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['warehouse'], name='stocklevel_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['warehouse', 'is_active'], name='location_wh_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['type'], name='location_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['status', 'move_type'], name='stockmove_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_date'], name='stockmove_date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['reference'], name='stockmove_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmoveline',
            index=models.Index(fields=['move'], name='stockmoveline_move_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'code'], name='warehouse_active_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.UniqueConstraint(fields=('adjustment', 'product', 'location'), name='uniq_inv_adj_line'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='uniq_product_barcode_when_set'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('default_sale_price__gte', 0)), name='product_default_sale_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('average_cost__gte', 0)), name='product_average_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('alt_factor__isnull', True), ('alt_factor__gt', 0), _connector='OR'), name='product_alt_factor_positive_when_set'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('weight_per_base__isnull', True), ('weight_per_base__gte', 0), _connector='OR'), name='product_weight_non_negative_when_set'),
        ),
        migrations.AddConstraint(
            model_name='reorderrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_qty__gte', 0)), name='reorder_min_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reorderrule',
            constraint=models.CheckConstraint(condition=models.Q(('target_qty__gte', 0)), name='reorder_target_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reorderrule',
            constraint=models.CheckConstraint(condition=models.Q(('multiple_of__isnull', True), ('multiple_of__gt', 0), _connector='OR'), name='reorder_multiple_positive_when_set'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'location'), name='uniq_stocklevel_prod_wh_loc'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='uniq_location_per_wh_code'),
        ),
        migrations.AddConstraint(
            model_name='stockmoveline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stockmoveline_qty_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockmoveline',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='stockmoveline_cost_non_negative'),
        ),
    ]
