# Generated by Django 5.2.8 on 2025-12-13 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryadjustmentline_unique_together_and_more'),
        ('uom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryadjustmentline',
            name='uniq_inv_adj_line',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_barcode_when_set',
        ),
        migrations.RemoveConstraint(
            model_name='reorderrule',
            name='uniq_reorder_rule_per_product_wh_loc',
        ),
        migrations.RemoveConstraint(
            model_name='stocklevel',
            name='uniq_stocklevel_prod_wh_loc',
        ),
        migrations.RemoveConstraint(
            model_name='stocklocation',
            name='uniq_location_per_wh_code',
        ),
        migrations.RemoveIndex(
            model_name='inventoryadjustmentline',
            name='invadjline_adj_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_barcode_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='prodcat_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='productcategory',
            name='prodcat_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='reorderrule',
            name='reorder_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklevel',
            name='stocklevel_wh_idx',
        ),
        migrations.RemoveIndex(
            model_name='stocklocation',
            name='location_wh_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmove',
            name='stockmove_status_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockmoveline',
            name='stockmoveline_move_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehouse',
            name='warehouse_active_code_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, verbose_name='كود المنتج (SKU)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='المعرّف (Slug)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=20, verbose_name='كود المستودع'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['is_deleted', 'warehouse'], name='invadj_del_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentline',
            index=models.Index(fields=['is_deleted', 'adjustment'], name='invadjline_del_adj_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deleted', 'is_active'], name='product_del_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_deleted', 'is_active'], name='prodcat_del_active_idx'),
        ),
        migrations.AddIndex(
            model_name='reorderrule',
            index=models.Index(fields=['is_deleted', 'is_active'], name='reorder_del_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['is_deleted', 'warehouse'], name='stocklevel_del_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['is_deleted', 'is_active'], name='location_del_active_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['warehouse'], name='location_wh_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['is_deleted', 'status'], name='stockmove_del_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['move_type'], name='stockmove_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmoveline',
            index=models.Index(fields=['is_deleted', 'move'], name='stockmoveline_del_move_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_deleted', 'is_active'], name='warehouse_del_active_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='warehouse_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('adjustment', 'product', 'location'), name='uniq_inv_adj_line_visible'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_product_code_visible'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='uniq_product_barcode_visible_when_set'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='uniq_prodcat_slug_visible'),
        ),
        migrations.AddConstraint(
            model_name='reorderrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'warehouse', 'location'), name='uniq_reorder_rule_visible'),
        ),
        migrations.AddConstraint(
            model_name='stocklevel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('product', 'warehouse', 'location'), name='uniq_stocklevel_prod_wh_loc_visible'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('warehouse', 'code'), name='uniq_location_wh_code_visible'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_warehouse_code_visible'),
        ),
    ]
