# Generated by Django 5.2.8 on 2025-11-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: length, weight, area, volume, unit, time.', max_length=50, unique=True, verbose_name='كود الفئة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم (إنجليزي)')),
                ('description', models.CharField(blank=True, help_text='وصف مختصر للفئة، اختياري.', max_length=255, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة؟')),
            ],
            options={
                'verbose_name': 'فئة وحدة قياس',
                'verbose_name_plural': 'فئات وحدات القياس',
                'ordering': ('code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='مثال: M, KG, PCS, ROLL.', max_length=50, unique=True, verbose_name='كود الوحدة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم الوحدة (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='اسم الوحدة (إنجليزي)')),
                ('symbol', models.CharField(blank=True, help_text='مثال: م, كجم, pcs (اختياري).', max_length=20, verbose_name='الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة؟')),
                ('notes', models.CharField(blank=True, help_text='أي ملاحظات إضافية عن هذه الوحدة (اختياري).', max_length=255, verbose_name='ملاحظات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='uom.uomcategory', verbose_name='فئة الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ('category', 'code', 'id'),
            },
        ),
    ]
