# Generated by Django 5.2.8 on 2025-12-09 18:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الدفتر')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدفتر')),
                ('type', models.CharField(choices=[('general', 'عام'), ('cash', 'كاش'), ('bank', 'بنك'), ('sales', 'مبيعات'), ('purchase', 'مشتريات')], default='general', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دفتر يومية',
                'verbose_name_plural': 'دفاتر اليومية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('method_type', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('card', 'بطاقة'), ('other', 'أخرى')], default='cash', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_due_days', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='أيام الاستحقاق')),
                ('auto_confirm_invoice', models.BooleanField(default=False, verbose_name='اعتماد تلقائي')),
                ('auto_post_to_ledger', models.BooleanField(default=False, verbose_name='ترحيل تلقائي')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة الضريبة %')),
                ('prices_include_vat', models.BooleanField(default=False, verbose_name='السعر شامل الضريبة')),
                ('default_terms', models.TextField(blank=True, verbose_name='شروط افتراضية')),
                ('footer_notes', models.TextField(blank=True, verbose_name='ملاحظات الفاتورة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الفواتير',
                'verbose_name_plural': 'إعدادات الفواتير',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('type', models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('allow_settlement', models.BooleanField(default=True, verbose_name='يقبل التسوية')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مقفلة؟')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'ordering': ['-year'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='fiscalyear_valid_dates')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('purchase', 'فاتورة مشتريات')], db_index=True, default='sales', max_length=20, verbose_name='نوع الفاتورة')),
                ('issued_at', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف العام')),
                ('terms', models.TextField(blank=True, verbose_name='الشروط')),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='المبلغ المدفوع (قديم، سيتم إلغاءه لاحقاً)')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('partially_paid', 'مدفوعة جزئياً'), ('paid', 'مدفوعة بالكامل'), ('cancelled', 'ملغاة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.contact', verbose_name='الطرف')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='سعر الوحدة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفاتورة',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='المرجع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('posted', models.BooleanField(default=False, verbose_name='مرحّل')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear', verbose_name='السنة المالية')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journal', verbose_name='الدفتر')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.CreateModel(
            name='LedgerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر البنك')),
                ('cash_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر الكاش')),
                ('closing_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر إقفال السنة')),
                ('default_manual_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر القيود اليدوية')),
                ('opening_balance_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر الرصيد الافتتاحي')),
                ('purchase_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر المشتريات')),
                ('sales_advance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب الدفعات المقدمة')),
                ('sales_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر المبيعات')),
                ('sales_receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب المدينون (العملاء)')),
                ('sales_revenue_0_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب المبيعات')),
                ('sales_vat_output_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب الضريبة المستحقة')),
            ],
            options={
                'verbose_name': 'إعدادات الدفاتر',
                'verbose_name_plural': 'إعدادات الدفاتر',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند صرف')], db_index=True, default='receipt', max_length=20, verbose_name='النوع')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ')),
                ('currency', models.CharField(default='OMR', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='مرجع خارجي')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconcile', to='contacts.contact', verbose_name='الطرف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconcile', to='accounting.journalentry')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.paymentmethod', verbose_name='طريقة الدفع')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='دائن')),
                ('reconciled', models.BooleanField(default=False, verbose_name='مُسوّى بالكامل')),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
                'ordering': ['order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='no_double_entry_in_line'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='no_zero_value_line')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, help_text='كم جزء من الدفعة تم تطبيقه على هذه الفاتورة.', max_digits=12, verbose_name='المبلغ المطبَّق')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.invoice', verbose_name='الفاتورة')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'تسوية دفعة مع فاتورة',
                'verbose_name_plural': 'تسويات الدفعات مع الفواتير',
                'ordering': ['-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.000'))), name='reconciliation_amount_positive'), models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_pair')],
            },
        ),
    ]
