# Generated by Django 5.2.8 on 2025-11-19 11:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('website', '0002_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', help_text='تظهر في بداية رقم الفاتورة مثل INV-2025-0001.', max_length=20, verbose_name='بادئة أرقام الفواتير')),
                ('invoice_padding', models.PositiveSmallIntegerField(default=4, help_text='مثلاً 4 تعني 0001، 0002، ...', verbose_name='عدد الخانات الرقمية')),
                ('invoice_reset_yearly', models.BooleanField(default=True, help_text='إذا كان مفعلًا، يبدأ الترقيم من 1 في كل سنة جديدة.', verbose_name='إعادة ترقيم الفواتير سنويًا؟')),
                ('default_due_days', models.PositiveSmallIntegerField(default=30, help_text='يُستخدم لحساب تاريخ الاستحقاق من تاريخ الفاتورة.', verbose_name='عدد أيام الاستحقاق الافتراضي')),
                ('auto_confirm_invoice', models.BooleanField(default=False, help_text='إذا كان مفعلًا، تنتقل الفاتورة من Draft إلى Sent تلقائيًا.', verbose_name='اعتماد الفاتورة تلقائيًا بعد الحفظ؟')),
                ('auto_post_to_ledger', models.BooleanField(default=False, help_text='إذا كان مفعلًا، يتم إنشاء قيد تلقائي في دفتر الأستاذ عند اعتماد الفاتورة.', verbose_name='ترحيل تلقائي إلى دفتر الأستاذ بعد الاعتماد؟')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='تُستخدم للفواتير التي تحتوي على ضريبة (يمكن تجاهلها إذا لم تُفعّل VAT).', max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة الافتراضية (%)')),
                ('prices_include_vat', models.BooleanField(default=False, help_text='إذا كان مفعلًا، تعتبر أسعار البنود شاملة للضريبة.', verbose_name='الأسعار شاملة للضريبة؟')),
                ('default_terms', models.TextField(blank=True, help_text='يتم نسخها تلقائيًا في حقل الشروط داخل الفاتورة الجديدة.', verbose_name='الشروط والأحكام الافتراضية')),
                ('footer_notes', models.TextField(blank=True, help_text='نص يظهر في أسفل الفاتورة المطبوعة (اختياري).', verbose_name='ملاحظات أسفل الفاتورة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعدادات المبيعات',
                'verbose_name_plural': 'إعدادات المبيعات',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tax_number', models.CharField(blank=True, help_text='Optional: VAT / Tax ID if applicable.', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional: link to a Django user for customer access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Human-readable invoice number, e.g. MAZ-2025-0001.', max_length=50, unique=True)),
                ('issued_at', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions shown on the invoice.')),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=3, default=0, help_text='Cached sum of related payments for quick display.', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer')),
                ('ledger_entry', models.OneToOneField(blank=True, help_text='Linked ledger journal entry for this invoice, if posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='ledger.journalentry')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار التأكيد'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('is_online', models.BooleanField(default=False, help_text='صحيح إذا كان الطلب تم من بوابة الزبون.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL, verbose_name='تم تأكيده بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='تم إدخاله بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounting.customer', verbose_name='الزبون')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='accounting.invoice', verbose_name='الفاتورة الناتجة')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.product', verbose_name='المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional: if linked, affects invoice paid_amount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.invoice')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['number'], name='accounting__number_1d02f2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='accounting__status_3055e0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_at'], name='accounting__issued__f5a872_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='accounting__date_e0610d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='accounting__custome_0f2c50_idx'),
        ),
    ]
