# Generated by Django 5.2.8 on 2025-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف'),
        ),
    ]
