# Generated by Django 5.2.8 on 2025-11-28 14:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, help_text='كم جزء من الدفعة تم تطبيقه على هذه الفاتورة.', max_digits=12, verbose_name='المبلغ المطبَّق')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تسوية دفعة مع فاتورة',
                'verbose_name_plural': 'تسويات الدفعات مع الفواتير',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='payment',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__status_3055e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__issued__f5a872_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__type_6e6809_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف العام'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='المبلغ المدفوع (قديم، سيتم إلغاءه لاحقاً)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, verbose_name='الشروط'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند صرف')], db_index=True, default='receipt', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.payment', verbose_name='الدفعة'),
        ),
        migrations.DeleteModel(
            name='PaymentAllocation',
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.000'))), name='reconciliation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_payment_invoice_pair'),
        ),
    ]
