# Generated by Django 5.2.8 on 2025-11-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('ledger', '0004_alter_journalentry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, help_text='Linked ledger journal entry for this invoice, if posted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='ledger.journalentry'),
        ),
    ]
