# Generated by Django 5.2.8 on 2025-11-25 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0002_remove_stockmove_product_remove_stockmove_quantity_and_more'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'بند طلب', 'verbose_name_plural': 'بنود الطلبات'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='uom.unitofmeasure', verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.product', verbose_name='المنتج'),
        ),
    ]
