# Generated by Django 5.2.8 on 2025-11-26 10:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='uom',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'حساب', 'verbose_name_plural': 'الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-issued_at', '-id'), 'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'بند فاتورة', 'verbose_name_plural': 'بنود الفاتورة'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'قيد يومية', 'verbose_name_plural': 'قيود اليومية'},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={'ordering': ['order', 'id'], 'verbose_name': 'سطر قيد', 'verbose_name_plural': 'سطور القيود'},
        ),
        migrations.RemoveConstraint(
            model_name='journalline',
            name='ledger_line_not_both_debit_credit',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__serial_b3ff63_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='number',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_custom_pattern',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_number_active',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_padding',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_prefix',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_reset_policy',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='invoice_start_value',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='order_custom_pattern',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='order_number_active',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='order_padding',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='order_prefix',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='order_reset_policy',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='order_start_value',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='payment_custom_pattern',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='payment_number_active',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='payment_padding',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='payment_prefix',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='payment_reset_policy',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='payment_start_value',
        ),
        migrations.AlterField(
            model_name='account',
            name='allow_settlement',
            field=models.BooleanField(default=True, help_text='السماح باستخدام الحساب في التسويات (عملاء/موردين).'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_default',
            field=models.BooleanField(default=False, help_text='تُستخدم كسنة افتراضية في التقارير.', verbose_name='سنة افتراضية للتقارير؟'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.contact', verbose_name='الزبون'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف عام'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, help_text='قيد الترحيل في دفتر الأستاذ إن وُجد.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry', verbose_name='قيد اليومية المرتبط'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='مجموع الدفعات المرتبطة (كاشد) لأغراض السرعة.', max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('partially_paid', 'مدفوعة جزئياً'), ('paid', 'مدفوعة بالكامل'), ('cancelled', 'ملغاة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, help_text='تظهر في الفاتورة للعميل.', verbose_name='الشروط والأحكام'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أنشئ في'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='bank_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_bank_journal', to='accounting.journal', verbose_name='دفتر البنك'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='cash_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_cash_journal', to='accounting.journal', verbose_name='دفتر الكاش'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='closing_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_closing_journal', to='accounting.journal', verbose_name='دفتر إقفال السنة'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='default_manual_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_default_manual_journal', to='accounting.journal', verbose_name='دفتر القيود اليدوية'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='opening_balance_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_opening_balance_journal', to='accounting.journal', verbose_name='دفتر الرصيد الافتتاحي'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='purchase_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_purchase_journal', to='accounting.journal', verbose_name='دفتر المشتريات'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_advance_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_advance_account', to='accounting.account', verbose_name='حساب دفعات مقدّمة من العملاء'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_journal',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_journal', to='accounting.journal', verbose_name='دفتر المبيعات'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_receivable_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_receivable_account', to='accounting.account', verbose_name='حساب العملاء (ذمم مدينة)'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_revenue_0_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_revenue_0_account', to='accounting.account', verbose_name='حساب المبيعات 0٪'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_vat_output_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_sales_vat_output_account', to='accounting.account', verbose_name='حساب ضريبة القيمة المضافة المستحقة (مخرجات)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='auto_confirm_invoice',
            field=models.BooleanField(default=False, help_text='إذا كان مفعلًا، تنتقل الفاتورة من مسودة إلى مُرسلة تلقائيًا.', verbose_name='اعتماد الفاتورة تلقائيًا بعد الحفظ؟'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_terms',
            field=models.TextField(blank=True, verbose_name='الشروط والأحكام الافتراضية'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='يمكن تجاهلها إن لم تُفعّل ضريبة VAT في النظام.', max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة الافتراضية (%)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات أسفل الفاتورة'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='prices_include_vat',
            field=models.BooleanField(default=False, verbose_name='الأسعار شاملة للضريبة؟'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journalline_not_both_debit_credit'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
