# Generated by Django 5.2.8 on 2025-11-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesSettings',
            new_name='Settings',
        ),
    ]
