# Generated by Django 5.2.8 on 2025-11-26 12:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_order_confirmed_by_remove_order_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'ordering': ['-year'], 'verbose_name': 'سنة مالية', 'verbose_name_plural': 'السنوات المالية'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'إعدادات الفواتير', 'verbose_name_plural': 'إعدادات الفواتير'},
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الحساب الأب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'أصل'), ('liability', 'التزامات'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='مجموع الدفعات المرتبطة (لأغراض السرعة فقط).', max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب السطر'),
        ),
    ]
