# Generated by Django 5.2.8 on 2025-11-19 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_rename_salessettings_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='invoice_reset_yearly',
        ),
        migrations.AddField(
            model_name='settings',
            name='invoice_custom_pattern',
            field=models.CharField(blank=True, help_text='اتركه فارغًا لاستخدام البادئة وعدد الخانات. يمكنك استخدام المتغيرات {year}، {month}، {day}، و {seq:04d}. يجب أن يحتوي النمط على {seq}.', max_length=100, verbose_name='نمط الترقيم المخصص (اختياري)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invoice_number_active',
            field=models.BooleanField(default=True, help_text='إذا تم تعطيله، لن يتم توليد أرقام تلقائية للفواتير.', verbose_name='تفعيل ترقيم الفواتير؟'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invoice_reset_policy',
            field=models.CharField(choices=[('never', 'لا يتم إعادة الترقيم'), ('year', 'يُعاد سنويًا'), ('month', 'يُعاد شهريًا')], default='year', help_text='تحدد متى يبدأ التسلسل من جديد: لا يعاد، أو سنويًا، أو شهريًا.', max_length=10, verbose_name='سياسة إعادة الترقيم'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invoice_start_value',
            field=models.PositiveIntegerField(default=1, help_text='مثلاً 1 تعني أن أول فاتورة ستكون 0001، ويمكن البدء من رقم أكبر عند الحاجة.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='قيمة البداية للتسلسل'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_due_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='يُستخدم لحساب تاريخ الاستحقاق من تاريخ الفاتورة.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='عدد أيام الاستحقاق الافتراضي'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='invoice_padding',
            field=models.PositiveSmallIntegerField(default=4, help_text='مثلاً 4 تعني 0001، 0002، ...', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='عدد الخانات الرقمية'),
        ),
    ]
