# Generated by Django 5.2.8 on 2025-11-18 19:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_invoice_ledger_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', help_text='تظهر في بداية رقم الفاتورة مثل INV-2025-0001.', max_length=20, verbose_name='بادئة أرقام الفواتير')),
                ('invoice_padding', models.PositiveSmallIntegerField(default=4, help_text='مثلاً 4 تعني 0001، 0002، ...', verbose_name='عدد الخانات الرقمية')),
                ('invoice_reset_yearly', models.BooleanField(default=True, help_text='إذا كان مفعلًا، يبدأ الترقيم من 1 في كل سنة جديدة.', verbose_name='إعادة ترقيم الفواتير سنويًا؟')),
                ('default_due_days', models.PositiveSmallIntegerField(default=30, help_text='يُستخدم لحساب تاريخ الاستحقاق من تاريخ الفاتورة.', verbose_name='عدد أيام الاستحقاق الافتراضي')),
                ('auto_confirm_invoice', models.BooleanField(default=False, help_text='إذا كان مفعلًا، تنتقل الفاتورة من Draft إلى Sent تلقائيًا.', verbose_name='اعتماد الفاتورة تلقائيًا بعد الحفظ؟')),
                ('auto_post_to_ledger', models.BooleanField(default=False, help_text='إذا كان مفعلًا، يتم إنشاء قيد تلقائي في دفتر الأستاذ عند اعتماد الفاتورة.', verbose_name='ترحيل تلقائي إلى دفتر الأستاذ بعد الاعتماد؟')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='تُستخدم للفواتير التي تحتوي على ضريبة (يمكن تجاهلها إذا لم تُفعّل VAT).', max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة الافتراضية (%)')),
                ('prices_include_vat', models.BooleanField(default=False, help_text='إذا كان مفعلًا، تعتبر أسعار البنود شاملة للضريبة.', verbose_name='الأسعار شاملة للضريبة؟')),
                ('default_terms', models.TextField(blank=True, help_text='يتم نسخها تلقائيًا في حقل الشروط داخل الفاتورة الجديدة.', verbose_name='الشروط والأحكام الافتراضية')),
                ('footer_notes', models.TextField(blank=True, help_text='نص يظهر في أسفل الفاتورة المطبوعة (اختياري).', verbose_name='ملاحظات أسفل الفاتورة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعدادات المبيعات',
                'verbose_name_plural': 'إعدادات المبيعات',
            },
        ),
    ]
