# Generated by Django 5.2.8 on 2025-11-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_orderitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_order', to='accounting.invoice', verbose_name='الفاتورة الناتجة'),
        ),
    ]
