# Generated by Django 5.2.8 on 2025-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_settings_invoice_reset_yearly_and_more'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__number_1d02f2_idx',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='serial',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['serial'], name='accounting__serial_b3ff63_idx'),
        ),
    ]
