# Generated by Django 5.2.8 on 2025-11-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_fiscalyear_options_alter_settings_options_and_more'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('purchase', 'فاتورة مشتريات')], db_index=True, default='sales', max_length=20, verbose_name='نوع الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(help_text='زبون في حالة المبيعات، ومورد في حالة المشتريات.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.contact', verbose_name='الطرف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, help_text='تظهر في الفاتورة للطرف.', verbose_name='الشروط والأحكام'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['type', 'status', 'issued_at'], name='accounting__type_b7f2e6_idx'),
        ),
    ]
