# Generated by Django 5.2.8 on 2025-11-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_invoice_accounting__number_1d02f2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='serial',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='رقم'),
        ),
    ]
