# Generated by Django 5.2.8 on 2025-11-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_invoice_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
