# Generated by Django 5.2.8 on 2025-11-27 14:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_invoice_type_alter_invoice_customer_and_more'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: نقدًا، تحويل بنكي، شيك...', max_length=100, verbose_name='اسم طريقة الدفع')),
                ('code', models.CharField(help_text='كود داخلي لتمييز طريقة الدفع (مثال: CASH, BANK_OMAN).', max_length=50, unique=True, verbose_name='الكود')),
                ('method_type', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('card', 'بطاقة'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='نوع الطريقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند صرف')], db_index=True, default='receipt', max_length=20, verbose_name='نوع الحركة')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='المبلغ')),
                ('currency', models.CharField(default='OMR', max_length=10, verbose_name='العملة')),
                ('reference', models.CharField(blank=True, help_text='مثال: رقم شيك، رقم عملية بنكية، رقم إيصال...', max_length=255, verbose_name='مرجع خارجي')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحَّل إلى الدفتر؟')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('contact', models.ForeignKey(help_text='العميل أو المورد المرتبط بهذه الحركة.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contacts.contact', verbose_name='الطرف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.journalentry', verbose_name='قيد اليومية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'دفعات',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المخصص للفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='accounting.invoice', verbose_name='الفاتورة')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'تخصيص دفعة لفاتورة',
                'verbose_name_plural': 'تخصيصات الدفعات للفواتير',
                'unique_together': {('payment', 'invoice')},
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='accounting__date_e0610d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contact'], name='accounting__contact_bea6a8_idx'),
        ),
    ]
