# Generated by Django 5.2.8 on 2025-11-28 10:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_paymentmethod_payment_paymentallocation_and_more'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['code'], 'verbose_name': 'دفتر يومية', 'verbose_name_plural': 'دفاتر اليومية'},
        ),
        migrations.AlterModelOptions(
            name='ledgersettings',
            options={'verbose_name': 'إعدادات الدفاتر', 'verbose_name_plural': 'إعدادات الدفاتر'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'verbose_name': 'تخصيص دفعة', 'verbose_name_plural': 'تخصيصات الدفعات'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'طريقة دفع', 'verbose_name_plural': 'طرق الدفع'},
        ),
        migrations.RemoveConstraint(
            model_name='fiscalyear',
            name='fiscalyear_start_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='journalline',
            name='journalline_not_both_debit_credit',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='accounting__type_b7f2e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='accounting__date_e0610d_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='accounting__contact_bea6a8_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='account',
            name='allow_settlement',
            field=models.BooleanField(default=True, verbose_name='يقبل التسوية'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account', verbose_name='الأب'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='افتراضية'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.contact', verbose_name='الطرف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True, verbose_name='الشروط والأحكام'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('general', 'عام'), ('cash', 'كاش'), ('bank', 'بنك'), ('sales', 'مبيعات'), ('purchase', 'مشتريات')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear', verbose_name='السنة المالية'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journal', verbose_name='الدفتر'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='القيد'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='bank_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر البنك'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='cash_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر الكاش'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='closing_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر إقفال السنة'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='default_manual_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر القيود اليدوية'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='opening_balance_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر الرصيد الافتتاحي'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='purchase_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر المشتريات'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_advance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب الدفعات المقدمة'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.journal', verbose_name='دفتر المبيعات'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب المدينون (العملاء)'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_revenue_0_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب المبيعات'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='sales_vat_output_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='حساب الضريبة المستحقة'),
        ),
        migrations.AlterField(
            model_name='ledgersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contacts.contact', verbose_name='الطرف'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='OMR', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='مرجع خارجي'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند صرف')], db_index=True, default='receipt', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='المبلغ المخصص'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('card', 'بطاقة'), ('other', 'أخرى')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='auto_confirm_invoice',
            field=models.BooleanField(default=False, verbose_name='اعتماد تلقائي'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='auto_post_to_ledger',
            field=models.BooleanField(default=False, verbose_name='ترحيل تلقائي'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_due_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MaxValueValidator(365)], verbose_name='أيام الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_terms',
            field=models.TextField(blank=True, verbose_name='شروط افتراضية'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='default_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة الضريبة %'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الفاتورة'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='prices_include_vat',
            field=models.BooleanField(default=False, verbose_name='السعر شامل الضريبة'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['type', 'status'], name='accounting__type_6e6809_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='fiscalyear_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='no_double_entry_in_line'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='no_zero_value_line'),
        ),
    ]
