# Generated by Django 5.2.8 on 2025-12-09 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('uom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('status', models.CharField(choices=[('draft', 'عرض سعر (مسودة)'), ('sent', 'عرض سعر (مرسل)'), ('confirmed', 'أمر بيع (مؤكد)'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('client_reference', models.CharField(blank=True, help_text='رقم الإشارة الخاص بالعميل أو رقم أمر الشراء.', max_length=50, verbose_name='مرجع العميل (PO)')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء/الصلاحية')),
                ('shipping_address', models.TextField(blank=True, verbose_name='عنوان الشحن')),
                ('billing_address', models.TextField(blank=True, verbose_name='عنوان الفوترة')),
                ('total_before_tax', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي قبل الضريبة')),
                ('total_tax', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='إجمالي الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي النهائي')),
                ('currency', models.CharField(default='OMR', max_length=3, verbose_name='العملة')),
                ('is_invoiced', models.BooleanField(default=False, verbose_name='مفوتر بالكامل')),
                ('delivery_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('partial', 'تسليم جزئي'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة التسليم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات للعميل')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='contacts.contact', verbose_name='العميل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مستند مبيعات',
                'verbose_name_plural': 'مستندات المبيعات',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد / تم التسليم'), ('cancelled', 'ملغي')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('order', models.ForeignKey(blank=True, limit_choices_to={'status': 'confirmed'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع')),
            ],
            options={
                'verbose_name': 'مذكرة تسليم',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesdocument')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'بند مبيعات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote')),
                ('sales_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='sales.salesline', verbose_name='بند الطلب')),
            ],
            options={
                'verbose_name': 'بند تسليم',
                'ordering': ('id',),
            },
        ),
    ]
