# Generated by Django 5.2.8 on 2025-11-26 09:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(blank=True, max_length=64, unique=True, verbose_name='رقم')),
                ('kind', models.CharField(choices=[('quotation', 'عرض سعر'), ('order', 'طلب بيع'), ('delivery_note', 'مذكرة تسليم')], db_index=True, default='quotation', max_length=20, verbose_name='نوع المستند')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('confirmed', 'مؤكد'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('invoiced', 'مفوتر')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, help_text='اختياري: تاريخ صلاحية عرض السعر أو تاريخ الاستحقاق.', null=True, verbose_name='تاريخ الانتهاء / صلاحية العرض')),
                ('total_before_tax', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي قبل الضريبة')),
                ('total_tax', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='إجمالي الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي النهائي')),
                ('currency', models.CharField(default='OMR', max_length=3, verbose_name='العملة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات تظهر للعميل في المستند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='contacts.contact', verbose_name='العميل / جهة الاتصال')),
                ('source_document', models.ForeignKey(blank=True, help_text='مثال: عرض السعر الذي تم إنشاء هذا الطلب منه.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='sales.salesdocument', verbose_name='المستند الأصلي')),
            ],
            options={
                'verbose_name': 'مستند مبيعات',
                'verbose_name_plural': 'مستندات المبيعات',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='يمكن تركه فارغاً ليتم استخدام اسم المنتج.', max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='بالنسبة المئوية %', max_digits=5, verbose_name='نسبة الخصم')),
                ('line_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي للسطر')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesdocument', verbose_name='المستند')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند مبيعات',
                'verbose_name_plural': 'بنود المبيعات',
                'ordering': ('id',),
            },
        ),
    ]
