# Generated by Django 5.2.8 on 2025-12-02 15:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التسليم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مذكرة تسليم',
                'verbose_name_plural': 'مذكرات التسليم',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('description', models.CharField(blank=True, help_text='يُستخدم اسم المنتج إذا تُرك فارغًا.', max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='الكمية المسلّمة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.product', verbose_name='المنتج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote', verbose_name='مذكرة التسليم')),
            ],
            options={
                'verbose_name': 'بند تسليم',
                'verbose_name_plural': 'بنود التسليم',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='المعرّف العام (UUID)')),
                ('kind', models.CharField(choices=[('quotation', 'عرض سعر'), ('order', 'أمر بيع')], db_index=True, default='quotation', max_length=20, verbose_name='نوع المستند')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('total_before_tax', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي قبل الضريبة')),
                ('total_tax', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='إجمالي الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='الإجمالي النهائي')),
                ('currency', models.CharField(default='OMR', max_length=3, verbose_name='العملة')),
                ('is_invoiced', models.BooleanField(default=False, help_text='يشير إلى أن أمر البيع تم فوترته.', verbose_name='مفوتر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات داخلية')),
                ('customer_notes', models.TextField(blank=True, verbose_name='ملاحظات للعميل')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='contacts.contact', verbose_name='العميل / جهة الاتصال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('source_document', models.ForeignKey(blank=True, help_text='يُستخدم لاحقاً للتسليم أو النسخ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='sales.salesdocument', verbose_name='المستند الأصلي')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مستند مبيعات',
                'verbose_name_plural': 'مستندات المبيعات',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(limit_choices_to={'kind': 'order'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع'),
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('description', models.CharField(blank=True, help_text='يُستخدم اسم المنتج إذا تُرك فارغًا.', max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم')),
                ('line_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='إجمالي السطر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesdocument', verbose_name='المستند')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_lines', to='inventory.product', verbose_name='المنتج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'بند مبيعات',
                'verbose_name_plural': 'بنود المبيعات',
                'ordering': ('id',),
            },
        ),
    ]
