# Generated by Django 5.2.8 on 2025-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟'),
        ),
    ]
