# Generated by Django 5.2.8 on 2025-11-29 15:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stocklevel_options_alter_stocklocation_options_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='is_invoiced',
            field=models.BooleanField(default=False, help_text='يشير إلى أن أمر البيع تم فوترته.', verbose_name='مفوتر'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات للعميل'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='kind',
            field=models.CharField(choices=[('quotation', 'عرض سعر'), ('order', 'أمر بيع')], db_index=True, default='quotation', max_length=20, verbose_name='نوع المستند'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='يُستخدم لاحقاً للتسليم أو النسخ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='sales.salesdocument', verbose_name='المستند الأصلي'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='description',
            field=models.CharField(blank=True, help_text='يُستخدم اسم المنتج إذا تُرك فارغًا.', max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='line_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='إجمالي السطر'),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ التسليم')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('order', models.ForeignKey(limit_choices_to={'kind': 'order'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع')),
            ],
            options={
                'verbose_name': 'مذكرة تسليم',
                'verbose_name_plural': 'مذكرات التسليم',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='يُستخدم اسم المنتج إذا تُرك فارغًا.', max_length=255, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='الكمية المسلّمة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.product', verbose_name='المنتج')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote', verbose_name='مذكرة التسليم')),
            ],
            options={
                'verbose_name': 'بند تسليم',
                'verbose_name_plural': 'بنود التسليم',
                'ordering': ('id',),
            },
        ),
    ]
