# Generated by Django 5.2.8 on 2025-12-03 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesline',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='الوحدة المستخدمة في هذا السطر (أساسية أو بديلة).', null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure', verbose_name='وحدة القياس'),
        ),
    ]
