# Generated by Django 5.2.8 on 2025-11-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='مثال: عرض السعر الذي تم إنشاء هذا الطلب منه.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='sales.salesdocument', verbose_name='المستند الأصلي'),
        ),
    ]
