# Generated by Django 5.2.8 on 2025-12-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sales', '0002_salesline_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='contacts.contact', verbose_name='العميل / جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(blank=True, help_text='اختياري: ربط مذكرة التسليم بأمر بيع معيّن.', limit_choices_to={'kind': 'order'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع'),
        ),
    ]
