# Generated by Django 5.2.8 on 2025-11-25 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesdocument_source_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='kind',
            field=models.CharField(choices=[('quotation', 'عرض سعر'), ('order', 'طلب بيع'), ('delivery_note', 'مذكرة تسليم')], db_index=True, default='quotation', max_length=20, verbose_name='نوع المستند'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('confirmed', 'مؤكد'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('invoiced', 'مفوتر')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
