# Generated by Django 5.2.8 on 2025-12-04 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sales', '0004_deliveryline_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='contacts.contact', verbose_name='العميل / جهة الاتصال'),
        ),
    ]
