# Generated by Django 5.2.8 on 2025-12-05 20:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sales', '0005_alter_deliverynote_contact'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryline',
            name='sales_line',
            field=models.ForeignKey(blank=True, help_text='السطر المرتبط في أمر البيع (لحساب الكميات المتبقية).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='sales.salesline', verbose_name='بند أمر البيع'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='client_reference',
            field=models.CharField(blank=True, help_text='رقم الإشارة الخاص بالعميل (PO Ref).', max_length=50, verbose_name='مرجع العميل / رقم طلب الشراء'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure', verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='contacts.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'order'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع المرتبط'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد / تم التسليم'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='تظهر في الطباعة للعميل (مثل شروط الدفع).', verbose_name='ملاحظات للعميل'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء / الصلاحية'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='is_invoiced',
            field=models.BooleanField(default=False, verbose_name='مفوتر بالكامل'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='notes',
            field=models.TextField(blank=True, help_text='ملاحظات لا تظهر للعميل.', verbose_name='ملاحظات داخلية'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='sales.salesdocument', verbose_name='المستند الأصلي'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='description',
            field=models.CharField(blank=True, help_text='يُستخدم اسم المنتج تلقائيًا إذا تُرِك فارغًا.', max_length=255, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='line_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='الكمية × السعر - الخصم', max_digits=14, verbose_name='إجمالي السطر'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure', verbose_name='وحدة القياس'),
        ),
    ]
