# Generated by Django 5.2.8 on 2025-12-06 10:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0006_deliveryline_sales_line_and_more'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryline',
            options={'ordering': ('id',), 'verbose_name': 'بند تسليم'},
        ),
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ('-date', '-id'), 'verbose_name': 'مذكرة تسليم'},
        ),
        migrations.AlterModelOptions(
            name='salesline',
            options={'ordering': ('id',), 'verbose_name': 'بند مبيعات'},
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='عنوان الفوترة'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('partial', 'تسليم جزئي'), ('delivered', 'تم التسليم')], default='pending', max_length=20, verbose_name='حالة التسليم'),
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='عنوان الشحن'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='sales_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_lines', to='sales.salesline', verbose_name='بند الطلب'),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(limit_choices_to={'kind': 'order'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد / تم التسليم'), ('cancelled', 'ملغي')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='client_reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='مرجع العميل (PO)'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_documents', to='contacts.contact', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='customer_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات للعميل'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصلاحية'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات داخلية'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesdocument'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='line_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesline',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure'),
        ),
    ]
