# Generated by Django 5.2.8 on 2025-12-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_deliveryline_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdocument',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='salesdocument',
            name='source_document',
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(limit_choices_to={'status': 'confirmed'}, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'عرض سعر (مسودة)'), ('sent', 'عرض سعر (مرسل)'), ('confirmed', 'أمر بيع (مؤكد)'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
