# Generated by Django 5.2.8 on 2025-12-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_salesdocument_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='order',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'confirmed'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='sales.salesdocument', verbose_name='أمر البيع'),
        ),
    ]
