# Generated by Django 5.2.8 on 2025-12-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_deliverynote_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdocument',
            name='client_reference',
            field=models.CharField(blank=True, help_text='رقم الإشارة الخاص بالعميل أو رقم أمر الشراء.', max_length=50, verbose_name='مرجع العميل (PO)'),
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء/الصلاحية'),
        ),
    ]
